### ISSUE TITLE
The mouse cursor doesn't hide automatically in the latest version "v109"

### ISSUE THREAD

**Issue by xZabuzax** [byuu/bsnes#101]
As the title suggest, the latest version v109 doesn't hide the mouse cursor automatically anymore in full-screen so I'm forced to move the mouse cursor to the corner of the screen to hide it myself.

**Comment by byuu** [comment]
By design for multi-monitor support, which would not be very useful if you couldn't use your mouse anymore. Set it to exclusive fullscreen mode if you want the cursor to hide. Barring that, use the F12 capture mouse hotkey toggle.
