### ISSUE TITLE
PPU `lightTable[]` initialization code variable names

### ISSUE THREAD

**Issue by JamesDunne** [byuu/bsnes#103]
FYI, this "issue" is a totally minor code variable naming thing that does not affect performance or stability in any way...

I was looking at the `PPU` class constructors to determine the proper RGB bit order that the SNES PPU deals with. I saw the the `r`, `g`, `b` variable names in `bsnes/sfc/ppu/ppu.cpp` (and `bsnes/sfc/ppu-fast/ppu.cpp`) constructors and looked at the `lightTable[]` initialization code which led me to believe that the PPU works in RGB bit order. While working on my own fork of the bsnes code (bsnes-angelscript if you're interested) and after banging my head against my desk for several hours trying to figure out why my custom rendering code writing to the 16-bit PPU `output` buffer had very odd-looking colors, I finally determined that my initial assumption about RGB order was incorrect. 🤦‍♂

In the `lightTable[l][(r << 10) + (g << 5) + b] = (ab << 10) + (ag << 5) + ar;` lines, I believe the `r` and `b` names should be swapped as well as `ar` and `ab`. As I'm sure you know (and I've recently discovered 🤣), the SNES PPU deals with colors in a `0BBBBBGGGGGRRRRR` order from most- to least-significant bit but the index expression there implies the opposite. I know this `lightTable[]` lookup effectively serves to swap the blue and red channels to map to the ARGB24 format output to the video drivers so it really doesn't matter what you call the variable names but I just thought I should point it out to you in case you considered it important enough to change.

Regardless, thank you for this amazing emulator! It's been such a joy to work with internally and is so much fun to experiment on top of.

**Comment by byuu** [comment]
RGB and BGR got swapped there because internally the SNES uses BGR colors, but externally the output from the light table is in RGB format.

**Comment by JamesDunne** [comment]
Right but I'm saying the variables are used backwards. The index expression should read `lightTable[l][(b << 10) + (g << 5) + r]` because that index is for the SNES PPU colors where blue is in the most significant bits, not red. Same for the assignment value which is in ARGB24 format.

**Comment by byuu** [comment]
Does it make any practical difference if I were to change them?

**Comment by JamesDunne** [comment]
To the compiler? No. It doesn't matter to the compiler what your variable names are 😄. To other humans? Yes, I think it makes a practical difference there since variable names play a large part in the reading and understanding of code.

**Comment by byuu** [comment]
Reviewing the code, I believe what I have to be correct even if it's not the easiest to read. So given it has no practical effect, I'd prefer to leave the code alone. Sorry to be a downer on your first issue request. Feel free to raise other issues with code going forward.

**Comment by JamesDunne** [comment]
No worries! Thank you for looking it over.
