### ISSUE TITLE
widescreen options

### ISSUE THREAD

**Issue by eadmaster** [byuu/bsnes#108]
the widescreen options that were in [bsnes-hd](https://github.com/DerKoun/bsnes-hd) seems were removed in the latest versions.

I would be nice to have them even if they produce garbage graphics with some games.

**Comment by bajolzas** [comment]
These option were never on the regular bsnes.
byuu said he will introduce a widescreen option if someone is able to make per-game widescreen patches. 
But without some kind of tutorial on how to do it I dont think it will happen any time soon.

**Comment by byuu** [comment]
bajolzas answered for me.
