### ISSUE TITLE
Wolfenstein 3-D Screen Corruption (v109.2)

### ISSUE THREAD

**Issue by Pr3ttyF1y** [byuu/bsnes#109]
The opening rotating graphic bubble displays a flickering line of corruption across the top of the screen using the standard/non-fast PPU.

[Wolfenstein-3-D-USA-003.png](https://postimg.cc/WhFWBX1J)

**Comment by Max833** [comment]
> Can someone test this one on real hardware, please?

Sure! 
http://streamable.com/4vd0o

**Comment by jjfmz42015** [comment]
Bug or overscan?

**Comment by kev4cards** [comment]
v108 works fine. v108.1 does not. Shows up with overscan area shown or removed. Setting CPU overclock to 105% moves the line off-screen (line becomes a thick white at 103%, moves upwards at 104%).

**Comment by byuu** [comment]
Fixed this by backporting higan's sprite caching into higan. The sprite caching was written after hard-forking bsnes.
