### ISSUE TITLE
Interest in HD Mode 7 perspective correction improvements (auto detect) for v108?

### ISSUE THREAD

**Issue by DerKoun** [byuu/bsnes#11]
Just wanted to check if you are interested in my latest HD Mode 7 improvements, especially perspective correction detection, for verison 108. I can separate it from widescreen and other features and put it in a pull request.

**Comment by byuu** [comment]
Extremely interested! I would be very appreciative of a pull request ^-^
Likewise if there's anything in v108 you'd really like in your fork, but need a hand with, please let me know.

**Comment by DerKoun** [comment]
I hope to get it done some time this week.
To update bsnes-hd I'll completely port my changes to v108 when that is stable. I'm sure I'll have to get back to you on that offer, thanks, appreciate it.

**Comment by DerKoun** [comment]
Just finished #14. May be a little rough here and there.
