### ISSUE TITLE
bsnes nightly started in fullscreen shows black screen due to nightly notification

### ISSUE THREAD

**Issue by Marat-Tanalin** [byuu/bsnes#111]
bsnes nightly shows black screen and does not run the game specified via command line along with the `--fullscreen` option, apparently due to the nightly-specific _notification window_ shown behind. Once the checkbox “Don’t show this message again” is checked, next full-screen starts are successfull.

**Comment by byuu** [comment]
Then check the box not to see it again.

**Comment by Marat-Tanalin** [comment]
Wouldn’t it make sense not to show the notification if bsnes is started in full-screen mode? The notification is not even visible when bsnes is started in full-screen mode, so the user just waits when the game starts, but nothing happens, just black screen instead of the game is shown which is somewhat confusing.

**Comment by Marat-Tanalin** [comment]
I suspect this can be fixed by replacing:

    if(Emulator::Version.find(".") && settings.general.betaWarning)

with

    if(!program.startFullScreen && Emulator::Version.find(".") && settings.general.betaWarning)

in the `bsnes.cpp` file.
