### ISSUE TITLE
Feature Request: Save State/Load State GUI

### ISSUE THREAD

**Issue by xZabuzax** [byuu/bsnes#113]
I know this will get ignored but I will post it anyways.

This is a feature that is available in the Mac/Os X version of Snes9X and isn't available anywhere else. The only emulator that has a feature somewhat similar are PPSSPP and Zsnes (this one looks plain ugly though) but the implementation of Snes9X is far better than those ones. I know I'm asking a lot but it would be cool having more emulators with a feature similar to that one.

This is the feature I'm talking about:
https://imgur.com/a/em3USoV

**Comment by byuu** [comment]
I followed the thread on NESdev. This isn't in scope now but I will keep the issue in mind, no promises however.
