### ISSUE TITLE
Firepower 2000 (USA) - Fast PPU Scanline Timing [bsnes v109.4][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#115]
Things are progressing (600/~3600 games tested).

This should be another game for your "per-game rendering position database", right? ^^

**bsnes v109.4 [Fast PPU off and hardware]:**  http://streamable.com/mhucb

**bsnes v109.4 [Fast PPU on]:** 

![image](https://user-images.githubusercontent.com/53529402/65039198-f820fa80-d951-11e9-9694-8550a8a78c78.png)
![image](https://user-images.githubusercontent.com/53529402/65039214-02db8f80-d952-11e9-8b24-6debb4240efc.png)

**Comment by jjfmz42015** [comment]
Renders perfect on Mesen-s DevWin 0.2.0.24

**Comment by Max833** [comment]
Yes, it's probably because of the pixel-based renderer. See: https://byuu.org/link:20190823_151509

**Comment by jjfmz42015** [comment]
if this was the reason the pixel ppu would render correct not incorrect.

also mesen-s is not a pixel render. yes ASP shadow works but Mesen stated he is scanline render.

**Comment by Max833** [comment]
> if this was the reason the pixel ppu would render correct [...]

Well... 
![image](https://user-images.githubusercontent.com/53529402/65079192-e6197900-d99e-11e9-8f9b-33eef8538726.png)


> also mesen-s is not a pixel render. [...]

It uses a pixel-based renderer.
 http://forums.nesdev.com/viewtopic.php?f=12&t=18658&sid=ed6042eb0117b53af275d848dff35e3b

**Comment by byuu** [comment]
Fixed by adding a rendering position override for this title when using the fast PPU. Thank you!
