### ISSUE TITLE
sameboy is now at 0.12.2 update bsnes?

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#116]
sameboy is now at 0.12.2 update bsnes?

maybe in future builds have it that sameboy rather than built in be loaded that way when sameboy gets an update user can download and install files into directory?

**Comment by byuu** [comment]
I can handle updating software at my pace, thank you for your concern.

**Comment by jjfmz42015** [comment]
was just a thought sorry if offended.
