### ISSUE TITLE
Ganso Pachinko Ou (Japan) [bsnes v110]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#118]
Hardware, Mesen-S, higan v106: http://streamable.com/0x8ju

bsnes (Fast PPU on and off) and snes9x: 

![image](https://user-images.githubusercontent.com/53529402/65334949-be572a80-dbc3-11e9-8214-2cf996c8c6cc.png)

**Comment by byuu** [comment]
It is asking you to disconnect the gamepad from controller port 2, which should only be used with the unemulated Pachinko controller.

In the future I might be able to add per-game controller configuration profiles.

**Comment by jjfmz42015** [comment]
Is it possible to disable game pad 2?

**Comment by Max833** [comment]
Ah, okay. Thanks byuu!

> Is it possible to disable game pad 2?

![112](https://user-images.githubusercontent.com/53529402/65354820-c11c4480-dbf0-11e9-804c-17c0b9af32ef.jpg)

**Comment by jjfmz42015** [comment]
ok now I feel stupid.


Thanks.

**Comment by byuu** [comment]
I'll close this because it's very, very out of scope right now to have a games database to auto-configure controller ports. But I'll make a note on my forum about this issue so that people know. Thanks for the report! Maybe one day I can emulate that Pachinko controller too.
