### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by MassHesteria** [byuu/bsnes#12]
I have been building bsnes locally since last year using msys64 and am now unable to build since the SameBoy integration. I get compiler warnings about "getline" and "vasprintf" in "gb.c" and "debugger.c". I also get linker errors for "getline". Quick Google search shows that this was a reported issue on SameBoy previously, but I have been unable to find a solution.

I also tried building with TDM-GCC with the same results.

**Comment by byuu** [comment]
Can you try editing nall/GNUmakefile line 42 from -std=c11 to -std=gnu11 ?
https://github.com/byuu/bsnes/blob/master/nall/GNUmakefile#L42
If this works, I'll add the fix upstream. Thanks!

**Comment by byuu** [comment]
Oh, also do this for line 47 please.
https://github.com/byuu/bsnes/blob/master/nall/GNUmakefile#L47

**Comment by MassHesteria** [comment]
Still seeing the same thing :/

I’ll play with that a little more tonight. Turn on verbose output from
make.

**Comment by MassHesteria** [comment]
Adding _GNU_SOURCE to the top of "gb.c" or adding it to the compiler lines (42 & 47) in "nall/GNUmakefile" gets rid of the vasprintf warning, but has no impact on the "getline" compiler warnings or linker errors.

**Comment by Screwtapello** [comment]
My `getline(3)` says:

> Both getline() and getdelim() were originally GNU extensions.  They were standardized in POSIX.1-2008.

...so I wouldn't expect `getline()` to be available on Windows, even with `_GNU_SOURCE` enabled. In this context I think "GNU extension" means an extension to *libc*, not to the C compiler, and MinGW uses the classic Visual Studio libc, not a port of glibc.

**Comment by LIJI32** [comment]
SameBoy might require some of these files to compile on Windows:

https://github.com/LIJI32/SameBoy/tree/master/Windows

**Comment by byuu** [comment]
I added _GNU_SOURCE to the top of gb.c.
How important is getline() for SGB emulation, LIJI? Can I just stub it out as a no-op function? Eg:
#define getline(l,n,s)

**Comment by LIJI32** [comment]
`getline` is only used in the default input handler for the debugger. You can just define `DISABLE_DEBUGGER` and remove `debugger.c` and `sm83_disassembler.c`. I think `_GNU_SOURCE` won't be required that way.

**Comment by MassHesteria** [comment]
That change resolves the "getline" compiler warnings and linker errors :+1: 

Still get the "vasprintf" error without the _GNU_SOURCE definition. Maybe this is good enough...

**Comment by byuu** [comment]
I merged LIJI's workaround.
