### ISSUE TITLE
Hanguk Pro Yagu (Korea) [bsnes v110]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#120]
Snes9x, Mesen-S and hardware: http://streamable.com/jsr65

bsnes:
![image](https://user-images.githubusercontent.com/53529402/65362027-27f82880-dc06-11e9-9655-07b8792522fc.png)

**Comment by byuu** [comment]
Region code bounding was wrong. Stopped at 0x12 for PAL rather than 12. Will be fixed in the next commit.
