### ISSUE TITLE
Excessive slowdown and flickering in some parts of Megaman X2 (LLE co-processor) [bsnes v110]

### ISSUE THREAD

**Issue by richterdeveloper** [byuu/bsnes#121]
I have noticed an excesive slowdown in some parts of Megaman X2 with LLE coprocessor emulation compared to the real hardware.
For example: when you defeat a boss and go to the "You Got weapon" screen, the animation is too slow and the blue bottom panel is flickering before appear.

This is from a real console (min. 7:32): https://www.youtube.com/watch?v=7-Lhbhw86mQ

**Comment by Max833** [comment]
Maybe your PC can't handle this game. How many frames a second do you get?

**Comment by byuu** [comment]
Looks like reloading cached pages only takes one step instead of two ... I really need to set up qwertymodo's Cx4 dev cart to explore these timings more, but it's pretty obvious from the results that things were too slow before.

So, this'll be corrected in the next WIP. Thanks!
