### ISSUE TITLE
Build nightlies in debug configuration for everyone to be able to provide backtrace

### ISSUE THREAD

**Issue by MT-ru** [byuu/bsnes#122]
Having prebuilt debug binaries would allow everyone to provide backtrace with no need to build from scratch on their own. That would be especially helpful for non-developers (most of emulator users are _not_ developers) as well as for developers using Visual Studio (bsnes can’t be built with VS).

Nightlies are for testing anyway, so it would be natural for them to be debug-ready by default. As an option, separate debug binaries could be provided besides the current nightlies.

**Comment by Screwtapello** [comment]
Debug builds are far too slow for most testing, so they couldn't be the default nightly build, but they might be a useful extra build.

Actually building bsnes in debug mode isn't all that difficult; finding a copy of gdb and loading the binary inside it is likely to be more tricky.

@byuu, you clearly have gdb running on Windows, where did you get it? Was it installed with your copy of gcc? Did you get it from cygwin or msys2? Is there some third-party gcc-for-Windows package people can download?

**Comment by MT-ru** [comment]
Fwiw, as we discovered with John on Discord, building Windows debug builds of bsnes does **not** work. The only way that worked for John was building under Linux using **cross-compilation**. He said:

> its officially built using a ubuntu image and cross compiling  
> i built it using the linux cross compilation approach  
> i suspect it really is broken when using mingw-make, and i dont know why  

Linus cross-compilation is unlikely suitable for most of Windows users. Official prebuilt debug binaries for Windows would help a lot.
