### ISSUE TITLE
Full Throttle - All-American Racing (USA) [bsnes v110.2][Fast PPU on and off]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#126]
![image](https://user-images.githubusercontent.com/53529402/65685267-e5997600-e061-11e9-9235-556d54d2861a.png)

Indeed, I've found it! =) 

> In jetsky races, on the left and right banks of the water it happens that the textures tremble and flicker.  A few months ago I had the opportunity to see the game running on a real console and realized that the problem does not occur.

Hardware and Mesen-S: https://streamable.com/7h41o
Snes9x v1.60, higan v106 and bsnes (Fast PPU on and off): https://streamable.com/0rsy3 (0:25)
@SourMesen

**Comment by byuu** [comment]
This one needs a new hardware test.

The game is writing to $420c (HDMA enable) at V=142, H=~1108-1110.
This is the starting point where HDMA starts running when enabled.
So it ends up being a race condition. When H<=1108, it causes HDMA to run on that scanline, which throws off the HDMA line table by one. That causes the screen to shake as it constantly hits and misses that point.

We must make an SNES test ROM that identifies exactly at which point the values written to $420c are latched. It is definitely H=1106 or earlier, and not H=1108 as I do now.

141,1108 : true
* w420c = 00 @ 142,500
142,1108 : false
* w420c = 1f @ 143,1108
143,1108 : true
144,1104 : true
145,1108 : true
146,1110 : true
147,1106 : true
148,1104 : true
149,1108 : true
150,1110 : true
151,1106 : true
152,1104 : true
153,1104 : true
154,1108 : true
155,1106 : true
156,1104 : true
157,1106 : true
158,1108 : true
159,1106 : true
160,1104 : true
0111 0000 0000 0111 00f4 03a5 0074 0251
161,1106 : true

141,1106 : true
* w420c = 00 @ 142,508
142,1104 : false
143,1104 : false
* w420c = 1f @ 143,1110
144,1110 : true
145,1106 : true
146,1108 : true
147,1104 : true
148,1108 : true
149,1104 : true
150,1106 : true
151,1108 : true
152,1104 : true
153,1108 : true
154,1106 : true
155,1108 : true
156,1104 : true
157,1106 : true
158,1104 : true
159,1108 : true
160,1106 : true
0124 0000 0000 0124 00f4 03a5 0074 024f
161,1108 : true

**Comment by undisbeliever** [comment]
This took a long time but I think I've written a new hardware test for this. ([source](https://github.com/undisbeliever/snes-test-roms))

[snes-test-roms-bins.zip](https://github.com/byuu/bsnes/files/3665366/snes-test-roms-bins.zip)

Attached are two SNES roms, which test setting `HDMAEN` mid-scanline.

The tests will test every HDMA channel at 13 different H-clock positions.
 * If the `sta HDMAEN` is latched then the Super Nintendo will display a red line. 
 * If the `sta HDMAEN` is not latched then no red line will be displayed

`hdmaen_latch_test.sfc` uses `HTIME` IRQ to set `HDMAEN` mid-scanline at H~= 1120 - 1074 for each HDMA channel. It's not very accurate, but works.
<br/>

The second test, `hdmaen_latch_test_2.sfc`, is bit more accurate and uses HTIME IRQ and cycle counting to set `HDMAEN` 2 master cycles later than the previous test.

It's not perfect, it took a lot of tweaking to get it to work as nicely as it does. According to bsnes-plus nearly all of the tests occur 2 master cycles after the previous one and occasionally a test will skip a few master cycles for some unknown reason (`sta $420c @ V: 40 H:1094 F: 1`, `sta $420c @ V: 42 H:1100 F: 1`).



I tried to use cycle counting to get the inner loop to execute in exactly 2 scanlines so I could eliminate the IRQ variance, but it just made everything worse (to the point where I had to rewrite hdmaen_latch_test_2.sfc).

---
Attached is a screen capture of hdmaen_latch_test_2.sfc working on my Super Famicom (CPU v2, PPU 1/3).

I do not know why DMA channel 0 has 4 lines. Maybe its that timing issue I wrote about above or maybe my code has a bug. I'm hoping you could shed some light on this issue.
![hdmaen_latch_test_2-2](https://user-images.githubusercontent.com/65687/65815724-acfec580-e236-11e9-93a0-a53ade9e50da.jpg)

**Comment by byuu** [comment]
Thank you very much for the test ROM. I was able to confirm I was latching the HDMA enable flags too late and corrected it. This doesn't regress Mecarobot Golf or any of my test_(h)dma test ROMs.

I wasn't able to get the lines to be 100% stable as in your screenshot, however, but at least we're better than before and Full Throttle is now working correctly.

The issue can be seen in https://github.com/byuu/bsnes/commit/07427e4697f947542e9e57c0af6bf8f91935d654 : trigger points are polled by the clock cycle, not by the opcode cycle.
