### ISSUE TITLE
Hurricanes (USA) - Scanline Timing [bsnes v110.2][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#128]
Attract mode level 12, time: 6:13:

https://abload.de/img/hurricanesusa1bj6d.jpg

Unfortunately I couldn't reproduce it again.

**Comment by byuu** [comment]
Noting @SourMesen, as this will affect Mesen-S once memory initialization is added.

This one's a bug in the original game. It's not actually related to the fast PPU renderer.
What happens is that it's transferring tile data from WRAM into VRAM without first initializing WRAM to zeroes.

So if you're unlucky, this bug will occur on real hardware.

I added a workaround to disable entropy when the "game hotfixes" option is enabled.

VRAM log:
040d = 485c
040e = 485b
040f = 0857
0410 = 4858
0411 = 4857
0412 = 4856
0413 = 4859
0414 = 0858
0415 = 0856
0416 = 0857
0417 = 0858
0418 = 0859
0419 = 0856
041a = 0857
041b = 0858
041c = 085a
041d = 085b
041e = 085c
041f = 0859
