### ISSUE TITLE
NHL '94 - Scanline Timing [bsnes v110.2][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#129]
Snes9x and bsnes (Fast PPU on): https://streamable.com/l8bcb
Hardware, bsnes (Fast PPU off) and Mesen-S: https://streamable.com/rrwev

Same issue:

NHL '94 (USA) (Beta)
NHL '94 (USA)
NHL Hockey '94 (Europe)
NHL Pro Hockey '94 (Japan)

**Comment by byuu** [comment]
Fixed, thank you.
