### ISSUE TITLE
Overclocking non-SuperFX processors?

### ISSUE THREAD

**Issue by Electricstar** [byuu/bsnes#13]
As the title says. This is something i've wanted to see in BSNES for a decent while now, the ability to overclock processors other than SuperFX. It's nice and all that we even get the option to overclock SuperFX, but considering how little games use it, its utility is a bit limited. I figured it would be nice to allow overclocking of the main SNES CPU and SA1 in particular, as it would affect a much more broad range of games, to either positive or negative effect depending on how much it's overclocked.

The idea particularly came back to me recently while playing Trials of Mana (Seiken Densetsu 3). Battles in ToM can get fairly unresponsive at times, from attacks taking a while to actually respond when hitting enemies, to the game's 'item wheels' becoming very sluggish at times, to Hi-res menus having very poor input response times, and just slowdown in general.

The one thing that worries me though is how BSNES might react to overclocking the main CPU, knowing its accuracy, since i'm aware a real SNES glitches out if you overclock even a little.

**Comment by byuu** [comment]
That's exactly my concern with it. The nice thing about overclocking the SuperFX is that even at 800% it really doesn't have any impact on compatibility, save for a glitchy start menu screen in Stunt Race FX once you're over 400%. Overclocking the CPU desyncs the other components (especially the SMP, used for streaming audio in games.) I'm definitely not opposed to the feature, but it will break games, so we have to find a way to offer it with a clear understanding not to report bugs when this inevitably happens. I'm expecting people to turn a setting like this on and then forget about it.

**Comment by Electricstar** [comment]
Best idea i'd have is maybe prompt a popup window when you touch the main CPU overclock slider, maybe along the lines of "WARNING! Overclocking main CPU will desync other components and may potentially result in severe glitches! Do not report bugs regarding overclocking the main CPU!" With two options: An "Okay" button that lets you proceed with overclocking and "Cancel" button that resets CPU clock to 100%. That's the best way I could imagine to catch the user's attention regarding bugs and bug reports.

**Comment by Screwtapello** [comment]
@SourMesen has been playing with a kind of overclocking in Mesen-S, and [apparently](https://forums.nesdev.com/viewtopic.php?p=241015#p241015) it's worked pretty well. It's more complex than just changing the emulated clock-rate, though —  it involves adding a bunch of hidden scanlines just before (or after) vblank.

You'd still need a warning message or similar, though.

**Comment by byuu** [comment]
This is added, we'll see what happens I guess ^^;
