### ISSUE TITLE
ADD TAS And ReRecording Features

### ISSUE THREAD

**Issue by DarkLegend1987** [byuu/bsnes#135]
Hi in beahalf of Long play community i request its you can ADD TAS tools movies and ReRecording support for Bsnes a great accurate emulator

**Comment by byuu** [comment]
I'm sorry but I must decline. That would be far too much work and would complicate the GUI for non-TAS users. I do offer movie recording, but beyond that, you'll really want to be using lsnes or BizHawk instead.
