### ISSUE TITLE
Audio drivers not remembering frequency setting

### ISSUE THREAD

**Issue by CharlesCorrin** [byuu/bsnes#137]
Go to Settings.

Go to Drivers.

Make audio driver be anything but WASAPI.

Set Frequency to something other than 48000. I use 44100.

Close the Settings and emulator. It will then forget the setting and revert to 48000.

**Comment by jjfmz42015** [comment]
Currently using 110.5 Commit 57c53a Winx64 and tried this. Happens to me as well.

**Comment by byuu** [comment]
Fixed in https://github.com/byuu/bsnes/commit/eaf33cb078bfc013982e7f34fdd4a9208a0b66e0

Thank you!
