### ISSUE TITLE
King of Rally, The - Paris-Moscow-Beijing (Japan) - flickering [bsnes v110.5][Fast PPU on and off]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#140]
bsnes, higan v106, Mesen-S and Snes9x: https://streamable.com/2nys0

Hardware: https://streamable.com/on90q

![b](https://user-images.githubusercontent.com/53529402/66242119-30218f00-e701-11e9-9986-595731ca9564.png)

**Comment by byuu** [comment]
So this game builds its sprite tables in WRAM at $032e+ (#$220 bytes.)

NMI occurs once per frame and DMAs this data into OAM at V=226-229.

The game's sprite building algorithm is a nightmare of jumps, no function calls, into densely interleaved code that is constantly loading dynamic variables to determine where to place sprites every frame, and this code runs always. From V=0-261. The point where the WRAM copy of OAM gets updated changes wildly from frame to frame. Where each sprite gets drawn to the WRAM copy also changes from frame to frame. The number of items, and thus the number of tiles, you guessed it, changes from frame to frame.

What I noticed in testing is that a "slight" overclock of 2% (way beyond the tolerance threshold of the SNES CPU oscillator) removes all of the flickering. But that's obviously not a correct fix.

Frankly, I'm completely stumped on this one.

I'd like to see more people test this on hardware just to rule out console variations.

I don't know how you find these hellish nightmare cases, but you sure have a knack for it.

**Comment by byuu** [comment]
With many thanks to the MiSTer Discord members, we have multiple confirmations that this does occur on real hardware. It seems to be a hardware difference. Max, can you let us know what kind of SNES system you have? Eg is it a 1CHIP? If you're not sure, no worries.
