### ISSUE TITLE
Last Github release is 109

### ISSUE THREAD

**Issue by KAMiKAZOW** [byuu/bsnes#141]
Please make releases on Github again instead of just numbered commits.

**Comment by jjfmz42015** [comment]
You just had to tarnish the zero issues lol.

**Comment by KAMiKAZOW** [comment]
It's not like clicking the "Draft a new release" button is so hard.

**Comment by byuu** [comment]
I'm not going to retroactively do it for v110 (Screwtape can tag it if he wants), but done for v111.

**Comment by KAMiKAZOW** [comment]
I don't care for past releases. I merely package bsnes for Linux and use Github's release tracking feature to get notifications of new releases. That's all.
