### ISSUE TITLE
[Feature Request] High Res Blending "Merge" Option

### ISSUE THREAD

**Issue by Awakened0** [byuu/bsnes#144]
Currently there is only a "Blur Emulation" option to blend high res mode transparency effects like in Kirby's Dreamland 3. [snes9x libretro has a "Merge" mode](https://github.com/libretro/snes9x/blob/29b78df8c9f0f48ed4605d08a187a134b3b316d6/libretro/libretro.cpp#L2048), which blends it without the blurriness. It works really well with CRT shaders designed for 240p too, since it seems to force the framebuffer down to 256x224 even when high res is active.

**Comment by Screwtapello** [comment]
Can you post a screenshot of "merge" mode versus "blend" mode? I'm having a hard time imagining what the difference would be.

**Comment by byuu** [comment]
That's reasonable. No promises on when, but I'm willing to implement it.

**Comment by Awakened0** [comment]
> Can you post a screenshot of "merge" mode versus "blend" mode? I'm having a hard time imagining what the difference would be.

Merge:
![merge](https://user-images.githubusercontent.com/4565863/66262924-be584c80-e7b7-11e9-8c96-30a7a5ace883.png)

Blur:
![blur](https://user-images.githubusercontent.com/4565863/66262927-c31d0080-e7b7-11e9-8fb0-99c1117a13dc.png)

If you look at the 02 near the bottom, you can see how it's blurrier with the blur method than with merge. Then if you look at Kirby's sprite, it's actually a bit blurrier in merge compared to blur, but it's consistent with the rest of the image. In that mode it looks like any other 256x224 game and the transparency looks normal too.

**Comment by byuu** [comment]
Oh, that is a *very* tiny difference ... my main thought as to why to add this would be so that you could use HQ2x in Kirby's Dream Land 3, but ... for such a small difference ... I'm not convinced it's worth making an already often-misunderstood issue more complicated. I'll think about it though.

**Comment by Awakened0** [comment]
Comparing snes9x's Merge Blending with bsnes' Blur Emulation at the beginning of the that stage:

snes9x Merge:
![snes9x merge](https://user-images.githubusercontent.com/4565863/66263640-404e7280-e7c4-11e9-8e1b-1c65a31932ae.png)

bsnes Blur:
![bsnes blur2](https://user-images.githubusercontent.com/4565863/66263643-4d6b6180-e7c4-11e9-8e2d-61afb9d6db34.png)

I think the blurring of the edges of the Kirby sprite is a little more noticeable with bsnes' Blur Emulation here. Once I get to where the transparent water is, it clears up. But then you get the slightly too sharp effect high res mode gives when paired with the CRT shader. I just think the merge style of blending gives you the most consistent experience.

**Comment by Screwtapello** [comment]
It's kind of hard to tell what's going on when the CRT scanline shader is adding its own blending on top. :/

So, in hi-res mode, each scanline is 512px wide. bsnes' "blur emulation" mode blends adjacent pixels, but keeps scanlines at 512px wide. For example, if you imagine `1` is a dim pixel and `9` is a bright pixel, and the SNES draws a scanline like `1357`, "blur emulation" would convert that into a scanline like `2266` with the same width, but pairs of pixels changed to their average.

The only other approach I can imagine would be to average pixels and produce a single output pixel for each pair, i.e. turning `1357` into `26` - like blur emulation, but half as wide. This would make the output 256px wide so it works nicely with filters like HQ2x, but I would expect it to be *blurrier* when scaled up, not sharper, since it has fewer pixels.

**Comment by Awakened0** [comment]
Here are comparisons of the two example areas without any shader: http://www.framecompare.com/image-compare/screenshotcomparison/J099JNNU

The clarity of the merge method over blur on the sprite is easier to see in these.

**Comment by Screwtapello** [comment]
Ah, yes. Everything else appears to be the same, but Kirby has a noticeable horizontal blur, particularly around the eyes.

**Comment by jjfmz42015** [comment]
To me it seems that the bsnes blur is a tad more blurry. Essentially this is what one would want enabling blur no? I mean if you wanted sharpness just turn it off. Or am I misunderstanding?

**Comment by Awakened0** [comment]
If you don't use any kind of blending you get lines instead of a cohesive transparency effect:

![Kirby's Dream Land 3 (USA)-191006-165649](https://user-images.githubusercontent.com/4565863/66275817-61fa3900-e85a-11e9-8516-a3358071da63.png)

**Comment by jjfmz42015** [comment]
Oh. Got you.

**Comment by byuu** [comment]
I'm going to politely decline this one for the time being.
The hires filtering already causes confusion and I feel a third option with only a minor difference will only create more confusion.

**Comment by Awakened0** [comment]
Fair enough. Thanks for the consideration :)
