### ISSUE TITLE
Website document error bsnes

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#147]
Bsnes document, no longer valid info

"Unlike Snes9X, bsnes only provides low-level emulation of SNES coprocessors. Thus, if you wish to play these games, you must obtain these files yourself and place them into the firmware directory first. Failure to do so will result in error messages when you run the aforementioned games."

**Comment by Screwtapello** [comment]
What do you mean by "website document"? I can't find the text you quote in [the bsnes website](https://bsnes.byuu.org/) or [the README](https://github.com/byuu/bsnes/blob/master/README.md).

**Comment by Sintendo** [comment]
The text can be found at https://doc.byuu.org/bsnes.

**Comment by byuu** [comment]
Yeah, there's HLE now I suppose.

I really don't like writing user documentation >_>

**Comment by jjfmz42015** [comment]
Just a suggestion. I mean I think any active bsnes users know.

**Comment by byuu** [comment]
I'll update the doc page later today.
