### ISSUE TITLE
Killer Instinct (Beta Version) does not boot on BSNES

### ISSUE THREAD

**Issue by icup321** [byuu/bsnes#148]
So there is a beta version of Killer Instinct out there, (not gonna link it, but it's easy to find) but the problem is that it doesn't boot on the vast majority of SNES emulators, including Higan and BSNES. However, I have noticed that it does seem to boot on older versions of BSNES and Higan, the last version of Higan I found that is able boot the game is v101. I'm not sure about BSNES, but I would assume it also broke compatibility on v102. This issue still happens on current versions and I don't know why. And yes, the ROM I have is clean and is No-Intro verified.

**Comment by Screwtapello** [comment]
My recollection is that the KI beta fails to boot if you do something one way, while a non-beta game fails if you do it the other way. Since it doesn't seem to be possible to get both games working in the same emulator, emudevs generally choose the officially released game over the beta.

**Comment by byuu** [comment]
Sorry, but I'm afraid I'm not willing to add hacks to the emulator to work around beta ROM bugs.
Most likely, like most betas, you'll need a custom manifest to run this game. They're usually issues with having bad internal headers. You could also patch the ROM -- perhaps betas could be distributed with BPS patches to correct the headers ...

**Comment by icup321** [comment]
Oh okay, I... somewhat see. I just managed to get it booting anyway by manually adding the ROM details to the Database file because I couldn't get the latest version of BSNES to load custom manifest files like Higan could for whatever reason (maybe I'm just being stupid and missed something in the options). I'm just gonna upload a custom database file here and maybe somewhere else in case people try to look for a workaround. I am closing this issue and am attaching a custom database file, unless you guys want to discuss about this any further.
[Super Famicom.zip](https://github.com/byuu/bsnes/files/3696160/Super.Famicom.zip)

**Comment by Screwtapello** [comment]
For the record, the extra entry in the database is:

```game
  sha256:   95328e72255e7b3162162d18dabe257a0df7353d874e5a943abb7f6fe5a10f87
  label:    BETA Killer Instinct
  name:     BETA Killer Instinct
  region:   SNS-AKLE-USA
  revision: SNS-AKLE-0
  board:    SHVC-1J0N-20
    memory
      type: ROM
      size: 0x400000
      content: Program
```

This is identical to the regular Killer Instinct (USA) entry, except for a different SHA256.

Meanwhile, the current version of bsnes autodetects the following manifest:

```
game
  sha256:   95328e72255e7b3162162d18dabe257a0df7353d874e5a943abb7f6fe5a10f87
  label:    Killer Instinct (USA) (Beta)
  name:     Killer Instinct (USA) (Beta)
  title:    Killer Instinct
  region:   NTSC
  revision: 1.0
  board:    LOROM-RAM
    memory
      type: ROM
      size: 0x400000
      content: Program
    memory
      type: RAM
      size: 0x40000
      content: Save
```

Is the problem literally just that the beta declares it expects save RAM and then crashes if it finds save RAM?
