### ISSUE TITLE
Kunio-kun no Dodge Ball Da yo Zenin Shuugou! - Tournament Special (Japan) - black screen.

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#151]
The game doesn't run.

**Comment by jjfmz42015** [comment]
confirmed.

**Comment by jjfmz42015** [comment]
I see. So for a rom to work it needs to be in the database.

Not that it matters I was just confirming as help.

Bsnes already does what I need it to. Seeing it grow has been fun.

**Comment by byuu** [comment]
added SHVC-2P3B-01
