### ISSUE TITLE
Nightly build error?

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#152]
The nightly build is showing 110.4 after 111.4. is this an error?
![Screenshot_2019-10-08-20-18-51](https://user-images.githubusercontent.com/18354277/66443152-f9eb5480-ea0b-11e9-96d6-9ee97f8a916b.jpg)

**Comment by byuu** [comment]
GitHub makes fixing typos a nightmare.

**Comment by jjfmz42015** [comment]
So it is typo then
