### ISSUE TITLE
Lufia II - Rise of the Sinistrals (USA) - black line (intro) [bsnes 111.4][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#154]
https://streamable.com/9k2sr

I don't see anything with Fast PPU off, Snes9x or Mesen-S.

Games with the same issue:

Lufia (Europe)
Lufia (Germany)
Lufia (Netherlands)
Lufia (Spain)

**Comment by byuu** [comment]
It would be trivial to add a scanline override, but no matter how many times I test this, I cannot reproduce it.

Guesses: you have rewind on, or CPU overclocking on, or something along those lines. If something else is wrong, then I don't know how to reproduce it, sorry.

![lufia2](https://user-images.githubusercontent.com/2107894/66534518-60c65600-eb51-11e9-8ea6-9633e8060b0a.png)
