### ISSUE TITLE
Supersampling graphic issues on Contra III

### ISSUE THREAD

**Issue by 1985a** [byuu/bsnes#156]
On stage2 at the top view, if you change the supersampling mode, it'll turn into this problem.

https://streamable.com/j6crd

Test it on Windows 10 1903 update.

edit: I don't know why but on my Arch Linux this problem is not present.

**Comment by Screwtapello** [comment]
Can you describe what the problem was, so that if I encounter somebody else with this problem in the future, I can tell them how to fix it?

**Comment by 1985a** [comment]
I think it was my fault due to by hit the box options supersampling. Those two options here.
https://imgur.com/bF7jcEC
