### ISSUE TITLE
NHL Pro Hockey '94 (Japan) - Scanline Timing [bsnes v111.4][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#157]
![image](https://user-images.githubusercontent.com/53529402/66671841-3792ec00-ec5d-11e9-8469-3070876014b5.png)

**Comment by byuu** [comment]
How incredibly annoying that we already did this game and missed the alternate region.

Good catch, I'll grab it in the next WIP.

**Comment by Max833** [comment]
Thanks!

I have a short question about something else: I want to play Mario Paint with my pc mouse, but I can't find a way to disable the windows mouse cursor ingame. What do I have to do?

**Comment by byuu** [comment]
F12 is the default binding for it, but you use the capture mouse functionality to do that.

**Comment by Max833** [comment]
Oh, there it is. >_<
What I really like about PCem is that the default binding to cover/recover mouse control is the mouse's third button. Is there a way to bind this as well?

**Comment by byuu** [comment]
Fixed, thank you.

Hmm, hotkeys are only bindable to keyboard keys right now. I'll take that under consideration however, it's a good idea for 2-button SNES mice. Although I do use the third button as the turbo toggle on the Super Scope ...
