### ISSUE TITLE
[Feature Request] Having the ability to view the Status Bar in Full-Screen mode

### ISSUE THREAD

**Issue by Apocalypse612** [byuu/bsnes#158]
I think this one is rather frustrating. You should be able to see the status bar within full-screen mode. Having to exit out of it each time you want to verify that you've changed / loaded / saved your state successful is rather irksome.

Thanks for your hard work!

**Comment by byuu** [comment]
This one is half-possible, same for the menubar.

What rules it out is exclusive mode. Exclusive mode takes over the Windows compositor and you can't use GUI elements anymore. You *must* be in exclusive mode to get the maximum latency reduction.

Further, adaptive sync (G-sync, Freesync, etc) only works if the video output covers 100% of the monitor and there is no GUI elements like a menubar.

Still, it's a fair amount of work to allow both, so I'll put this one down as a "useful feature, maybe add if I can." Thanks for the suggestion.

**Comment by Apocalypse612** [comment]
If it's too much work, then perhaps just a way to see (with a temporary text overlay that fades out, on top of the existing graphics) when save states are changed / loaded / saved, etc. I'm unsure if it would conflict with adaptive sync and exlusive mode in this scenario.

**Comment by jjfmz42015** [comment]
Why not what snes9x and many others do. Have text display osd of room and checksum loaded. Also have option for odd fps.

This would eliminate need for status bar and work regardless of window, full screen or exclusive.

**Comment by byuu** [comment]
I don't want to implement a text renderer into the video output stream. The video output stream can be anywhere from 256x224 to 3840x2160.

I added a new pseudo-fullscreen toggle setting that will let you go fullscreen with the status bar visible, hopefully this works.
