### ISSUE TITLE
[Feature Request] Default directories inside Emulator root directory for Saves, States, Screenshots, etc

### ISSUE THREAD

**Issue by Apocalypse612** [byuu/bsnes#159]
Hello there,

I'm suggesting that default folder path infrastructure for Saves, States, and Screenshots should all be within the root folder of the Emulator (instead of where you loaded the game from). Having it set up this way is rather odd, and I honestly cant say I know of another emulator that behaves in this manner. Cheats and Patches should probably be there also. 

Cheers!

**Comment by byuu** [comment]
If that's the case, then people upgrading to a new version would suddenly find all their saves missing. The paths are also absolute and not relative, so I wouldn't have any idea what a person's Windows username was or where they'd be extracting the emulator to.

Different people have different feelings about what should be split to other paths and what shouldn't. Eg some might want patch files next to the ROMs, others might want them separated.

What you could do is delete the settings.bml file to make bsnes' settings permanent, set up your paths one time, and then it's done forever for you.

Given that, I'd politely decline to make this change.

**Comment by Apocalypse612** [comment]
Fair enough, I think I'll do that. Thanks!
