### ISSUE TITLE
[Feature Request] DSP Gaussian Interpolation

### ISSUE THREAD

**Issue by Passingby1** [byuu/bsnes#160]
The latest version of Bsnes has really bad bass response when compared to other emulators, including but not limited to Higan itself, which is pretty decent in this regard. The others are Messen-S and Snes9x, both better than Higan on this department. The situation can be partially worked around using the Retroarch core with Retroarch's LowPassCPS DSP plugin. 

It could be a bug given how Higan itself sounds better on games like Yoshi's Island. 

It'd be nice to have Gaussian Interpolation besides the Cubic one, which btw when used kills bass response even more on Bsnes.

**Comment by byuu** [comment]
The default when cubic isn't checked *is* gaussian interpolation.

The digital audio output from bsnes is 100% bit-perfect to the original hardware, which we have confirmed many times over with test ROMs sampling the echo buffer from the SNES.

If other emulators sound better, it's because they sound less accurate.

**Comment by Passingby1** [comment]
Then something could be wrong with the latest version, it sounds...flat, nothing like the SNES, even very old revisions of Bsnes sound better, not to mention Higan, and I don't think Higan is less accurate too.

**Comment by Max833** [comment]
bsnes 111.5 vs higan 106:

https://streamable.com/rthfb

bsnes sounds exactly like higan.

**Comment by Passingby1** [comment]
> bsnes sounds exactly like higan.

Both sound far from exactly the same, bass response is better on Higan, I'm sorry, it just doesn't, even when you had lower volume on the Higan window. Get better sound hardware if they sound exactly the same to you on your end.

It surely strikes me as odd is how Byuu claims other emulators are less accurate, therefore sound better, when I was including Higan among the list of emulators that sound better than Bsnes.

**Comment by byuu** [comment]
We have test ROMs that validate the output is 100% bit-perfect. bsnes and higan sound identical to me on my $250 Audio Technica headphones on a dedicated sound card with ASIO. I have nothing to work with in this report, so unless you have a patch or some demonstrable proof, there's nothing more to be done here.
