### ISSUE TITLE
v111r3 - HD mode 7 image jumps occasionally

### ISSUE THREAD

**Issue by DanKorell** [byuu/bsnes#161]
Just updated to v111r3 and loaded up A Link to the Past. I'm using the xBRZ Freescale shader if this makes any difference, and using both a x4 mulitplier for the screensize and the 960p option for the HD mode 7.

Now, when viewing the map, which uses mode 7, the graphics still look great, but I noticed that every couple of seconds the image would jump slightly, which is odd as the map itself is static (when zoomed out to show the whole map) so shouldn't have any movement at all.

This did not happen in v110 which is the previous version I was using.

**Comment by Max833** [comment]
Yeah, this was an issue with v111r3 (https://github.com/byuu/bsnes/issues/150). Disable rewind (emulator -> rewind -> frequency) or load the latest version v111r5 (https://github.com/byuu/bsnes/commits/master) and it should work.

**Comment by byuu** [comment]
We'll mark it as resolved.

Point noted that I need to post a new build on byuu.org
