### ISSUE TITLE
Las Vegas Dream in Golden Paradise (Japan) - Scanline Timing [bsnes v111.5][Fast PPU on and off]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#162]
bsnes (Fast PPU on and off), Snes9x 1.60 and Mesen-S:

https://streamable.com/1mq9t

Hardware:

https://streamable.com/91xsr

All emulators have the same issue. I hope that's not again just my SNES. 

**Edit:**
'>_>

![image](https://user-images.githubusercontent.com/53529402/66702453-0ae7de80-ed08-11e9-8d93-e31b6a02c247.png)

**Comment by byuu** [comment]
Good one for byuu.net in any case
