### ISSUE TITLE
Exclusive full screen resolution selection

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#163]
Would be nice if user could set target resolution for exclusive full screen mode. People run PC's in all kinds of different configurations in many cases their desktop resolution is not ideal resolution for their emulator. This can help if user wants a lower res for horsepower or higher res for looks than their preferred desktop setting.

You learn the value of this when having multiple setups all in different display configs and having experienced emulators that allow such function examples snes9x, mednafen, kega fusion, etc.

**Comment by byuu** [comment]
I really don't want to do this. It would only benefit the Direct3D driver alone, and I want OpenGL to be the default. So I'm going to politely decline.

**Comment by jjfmz42015** [comment]
Ok thank you. Can I ask how it doesn't effect open gl?

**Comment by Screwtapello** [comment]
The OpenGL API doesn't provide a way to set a target resolution.

**Comment by jjfmz42015** [comment]
Mednafen is open gl only no d3d. It does this. Which is nice for people with a media center on 4k screen. I use a 720p desktop in this scenario but run my emulators etc in 4k so that my scanlines look proper and not fat
