### ISSUE TITLE
Submodule for sameboy

### ISSUE THREAD

**Issue by fr500** [byuu/bsnes#168]
Hey

Have you considered using a submodule for sameboy so it can always track upstream?
I think it would be mutually beneficial.

**Comment by fr500** [comment]
Just wondering btw

**Comment by Screwtapello** [comment]
Even a submodule would be pinned to a particular revision of SameBoy, so it wouldn't always track upstream.

The real answer, though, is that bsnes isn't developed in Git, it's just exported to a Git repo to make it easier for people to look at. Managing a submodule would be even more work for bsnes than it is for most Git repos, and even for regular Git-based projects submodules are a bigger hassle than plain Git.

**Comment by byuu** [comment]
Eventually we'll reach a point where you can just drop a SameBoy core/ folder into bsnes and the upgrade is complete. But right now, bsnes requires a few key patches to SameBoy to work.

**Comment by fr500** [comment]
Thanks for getting back to me
