### ISSUE TITLE
OpenMP dependency for libretro core

### ISSUE THREAD

**Issue by fr500** [byuu/bsnes#169]
Hello

Libretro core seems to depend on OpenMP (on windows at least)

```
$ ntldd out/*
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x0000000000620000)
        msvcrt.dll => C:\Windows\SYSTEM32\msvcrt.dll (0x0000000000620000)
        libgomp-1.dll => D:\Tools\msys64\mingw64\bin\libgomp-1.dll (0x0000000000190000)
        libstdc++-6.dll => D:\Tools\msys64\mingw64\bin\libstdc++-6.dll (0x00000000033d0000)
```

Is this neccesary? Core seems to work fine without it.

**Comment by Screwtapello** [comment]
OpenMP is used to render scanlines in parallel, when "Fast PPU" mode is enabled, which is the thing that makes the "HD Mode 7" effect possible.

**Comment by byuu** [comment]
Yes, it's very much required. See https://i.imgur.com/32ArSVT.png for why.
You can compile without it if you really want, but you shouldn't.

**Comment by fr500** [comment]
Alright thanks for the response.
I thought HD mode 7 worked without it last night I tested it but I may have
screwed up.

I'll see if it's possible to link it statically for the libretro buildbot.
