### ISSUE TITLE
Feature request windows version

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#170]
Allow file browser to use bigger font. This is a nice option for those of us using a PC on a large screen at a distance.

Also possibly the ability of screen shot preview in the file selection screen.

**Comment by byuu** [comment]
It responds to your Windows GUI scale setting. Increase your Windows GUI size to 150% or 200% and the fonts everywhere will get bigger.

**Comment by jjfmz42015** [comment]
Thats what Im doing now. However this breaks certain apps.


I used medgui for mednaffen the other day it had this feature and thought it was a good idea, this is where the suggestion comes from.

So I suggested it in case its easy and others might like it?


Either way thank you.
