### ISSUE TITLE
bsnes libretro target doesn't compile with libretro_super build scripts

### ISSUE THREAD

**Issue by cprivite** [byuu/bsnes#171]
I'm not sure if this is an issue that should be tracked here or on the libretro_super GitHub, so here's a link to the issue I opened over there. https://github.com/libretro/libretro-super/issues/1146.

And here's the output:
`
cprivite@Mac-mini libretro-super % ./libretro-build-ios-arm64.sh bsnes_hd uname: illegal option -- o usage: uname [-amnprsv] CC = cc -arch arm64 -marm -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk CXX = c++ -arch arm64 -marm -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk CXX11 = clang++ -std=c++11 -stdlib=libc++ -arch arm64 -marm -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk CXX17 = clang++ -std=c++17 -stdlib=libc++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk STRIP = Compiler: CC="cc -arch arm64 -marm -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk" CXX="c++ -arch arm64 -marm -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk" === iOS == ios-arm64 ios-arm64 === bsnes HD Building bsnes_hd... cd "/Volumes/Storage/RetroArch/libretro-super/libretro-bsnes_hd/bsnes" make -f GNUmakefile platform="ios-arm64" -j7 compiler="clang++ -std=c++17 -stdlib=libc++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk" target="libretro" clean make: 'clean' is up to date. make -f GNUmakefile platform="ios-arm64" -j7 CC="cc -arch arm64 -marm -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk" CXX="c++ -arch arm64 -marm -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk" compiler="clang++ -std=c++17 -stdlib=libc++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk" target="libretro" Compiling target-libretro/libretro.cpp ... Compiling ../libco/libco.c ... Compiling emulator/emulator.cpp ... Compiling filter/filter.cpp ... Compiling lzma/lzma.cpp ... Compiling sfc/interface/interface.cpp ... Compiling sfc/system/system.cpp ... Compiling sfc/controller/controller.cpp ... clangclang: error: the clang compiler does not support '-march=native'clang: error: the clang compiler does not support '-march=native'clangclangclang: clang: : errorerror: : errorthe clang compiler does not support '-march=native': the clang compiler does not support '-march=native': errorerror: : the clang compiler does not support '-march=native'the clang compiler does not support '-march=native': the clang compiler does not support '-march=native' clang: error: unsupported option '-fopenmp' clang: errorclang: error: unsupported option '-fopenmp' clang: error: unsupported option '-fopenmp' clang: error: unsupported option '-fopenmp' clang: error: unsupported option '-fopenmp' clang: error: unsupported option '-fopenmp' : unsupported option '-fopenmp' make: *** [obj/sfc-system.o] Error 1 make: *** Waiting for unfinished jobs.... make: *** [obj/lzma.o] Error 1 make: *** [obj/libco.o] Error 1 make: *** [obj/libretro.o] Error 1 make: *** [obj/filter.o] Error 1 make: *** [obj/sfc-interface.o] Error 1 make: *** [obj/emulator.o] Error 1 cp "out/bsnes_hd_libretro_ios.dylib" "/Volumes/Storage/RetroArch/libretro-super/dist/ios-arm64/bsnes_hd_libretro_ios.dylib" cp: out/bsnes_hd_libretro_ios.dylib: No such file or directory 1 core(s) failed: bsnes_hd
`
Environment is macOS 10.15, Xcode 11.1.
Xcode-select -p is "/Applications/Xcode.app/Contents/Developer"

**Comment by Screwtapello** [comment]
I don't think libretro compilation is supported anywhere but on the RetroArch build-servers. It's understandable that you can't use `-march=native` when cross-compiling for iOS, and there's a makefile variable you can set to skip that flag, but `-fopenmp` is quite important for Fast PPU mode, which helps bsnes run at a playable speed on low-power devices.

Also, the bsnes core is just "bsnes", not "bsnes_hd", since that's the name of [DerKoun's fork](https://github.com/DerKoun/bsnes-hd) (which does not currently have a libretro core, but might in the future).

**Comment by byuu** [comment]
Yeah, I'll tag @rtretiakov so he's aware, but I'm not actively maintaining these build rules, sorry.

**Comment by cprivite** [comment]
> I don't think libretro compilation is supported anywhere but on the RetroArch build-servers. It's understandable that you can't use `-march=native` when cross-compiling for iOS, and there's a makefile variable you can set to skip that flag, but `-fopenmp` is quite important for Fast PPU mode, which helps bsnes run at a playable speed on low-power devices.
> 
> Also, the bsnes core is just "bsnes", not "bsnes_hd", since that's the name of [DerKoun's fork](https://github.com/DerKoun/bsnes-hd) (which does not currently have a libretro core, but might in the future).

So this is why I wanted to bring you guys into this discussion cause it's clear there's mis communication between the two projects. The actual upstream core for bsnes that has byuu's code IS called bsnes_hd in the libretro_super project. You can see this section of the rules.d/core-rules.sh file that sets up where the code for bsnes_hd is pulled from:
`include_core_bsnes_hd() {
	register_module core "bsnes_hd" -theos_ios -ngc -sncps3 -ps3 -psp1 -qnx -wii
}

libretro_bsnes_hd_name="bsnes HD"
libretro_bsnes_hd_git_url="https://github.com/libretro/bsnes.git"
libretro_bsnes_hd_build_args="compiler=\"${CXX17}\" target=\"libretro\""
libretro_bsnes_hd_build_subdir="bsnes"
libretro_bsnes_hd_build_makefile="GNUmakefile"
libretro_bsnes_hd_build_products="out"`

If you check on that repo you'll see it's a fork from byuu/bsnes that varies by 3 commits (2 ahead, 1 behind as of this posting).

The one just referred to as "bsnes" doesn't compile at all and has been dropped from the project at this point.

I don't fully understand what's giong on with the fopenmp stuff right now and can only say that fully removing all references to it is the only way to get the core to compile.

However, the -march=native stuff is getting pulled in as the compile script is calling its make from the bsnes subdirectory and isn't overriding the local variable, so it stays set as "true" and thus includes -march=native even though it's trying to cross compile for iOS.

Anyway, thanks, as I figured out what to put in this post I think I learned a lot more about how this is all glued together so I'll go post this issue on @rtretiakov 's repo since it seems the better place for this.
