### ISSUE TITLE
Star Ocean (Japan) - run-ahead

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#173]
I was messing around with v111.8 and I've found a glitch in the game with run-ahead (one frame) enabled. The sound is crackling as well.

**Edit:** Everything looks fine when I use fast forward and enter the house.

**Edit 2:** Could it be that my notebook is not powerful enough and that's the reason why I have frame drops, crackling sound and glitches (i5-8250u @ 3,4 GHz)?

**Edit 3:** The strange thing is that no other game behaves like this.

**Edit 4:** Wow, the more I play with this run-ahead feature... it's absolutely brilliant! ^_^

https://streamable.com/f2s3l

![image](https://user-images.githubusercontent.com/53529402/66849029-7505bb00-ef76-11e9-94c2-799fc893dded.png) 
![image](https://user-images.githubusercontent.com/53529402/66849040-7b943280-ef76-11e9-89de-d71f23893536.png)

**Comment by jjfmz42015** [comment]
I can test later and report back. Have a few high powered systems. Never played Star ocean. So I'm not sure what I will be looking for. Might come back and report or ask for guidance. If it's cpu mine won't be a issue I'll run it on my i7-8700k

**Comment by byuu** [comment]
I fixed it. I wasn't serializing the decompressor state because before deterministic save states it wasn't possible to stop in the middle of a decompression sequence.

**Comment by Max833** [comment]
Everything else is fixed in v111.11, but it looks like this is still a problem.
