### ISSUE TITLE
latest release 111.9 again ships with rewind enabled in settings.bml

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#176]
just a heads up

latest release 111.9 again ships with rewind enabled in settings.bml

since this breaks games Ide ship with it disabled. New users wont know that this is breaking stuff.

**Comment by Screwtapello** [comment]
111.9 adds a new serialisation method that should work perfectly for rewind and runahead, so it's OK to ship rewind enabled by default again (unless new problems are found in 111.9).

**Comment by byuu** [comment]
Concur with Screwtape, it'll be off for v112. Good to stress test the new serialization method in the mean-time.
