### ISSUE TITLE
Background rendering improperly in Super Metroid

### ISSUE THREAD

**Issue by MassHesteria** [byuu/bsnes#18]
As I've been playing with newer versions of bsnes I noticed some improper drawing of the background in Super Metroid when Samus first lands on the planet. Initially I thought it was strictly related to the new filters (which look great BTW), but I realized that it is not. I've attached a screen shot of bsnes 107r3 vs 107r11. I just checked, and I have bsnes 107r6 built as well and it also has the improper background.

![sm-107r3-vs-107r11](https://user-images.githubusercontent.com/1452105/61839281-9ca32680-ae52-11e9-97cc-b166b54f990a.png)

**Comment by Screwtapello** [comment]
That looks like a version of Super Metroid modified for speed-running. I checked the original Super Metroid with bsnes revision 73f0b7bb, stood in that spot for 10 seconds, and couldn't reproduce the problem you found.

**Comment by MassHesteria** [comment]
The error actually occurs in both the practice rom and the original Super Metroid rom. New screenshot uses the proper file and includes hashes. I am also running revision #73f0b7b on Windows. Also, the drawing issue is constant and stays in place as samus moves. Definitely in the background though as you can go up the hill and samus will block the improperly draw part of the background.

![sm-107r3-vs-107r13](https://user-images.githubusercontent.com/1452105/61843170-5c4aa500-ae60-11e9-8f24-a5b160e9aff7.png)

**Comment by byuu** [comment]
Definitely include settings when reporting bugs with bsnes, please. Is fast PPU enabled? I'll look into it in any case, thanks.

**Comment by MassHesteria** [comment]
So I decided to start rolling back revisions to determine when the issue initially showed up. I first see it in 107r5 (revision a03d91882c30d9becce5a61740109d163f61287c). I've attached screen shots of my Emulator, Driver, and Video settings using 107r5. These match 100% with 107r3 except for the existence of the "Skip frames will fast forwarding" checkbox. Fast PPU is enabled on all versions I have been testing.

![bsnes-107r5-settings](https://user-images.githubusercontent.com/1452105/61870749-7efead00-aea4-11e9-834c-32183d102c0a.png)

Also, just wanted to say "thank you" to you (byuu) and ScrewTape for this great project. I've been following closely since the reboot, and it has been awesome seeing all the great work being done.

**Comment by MassHesteria** [comment]
And it does appear to be caused by the Fast PPU. Just tried disabling it and reloading the game and the issue goes away. Hopefully that helps narrow things down :male_detective:

**Comment by byuu** [comment]
I just tried with and without the fast PPU, and I cannot reproduce this.

I absolutely believe you're experiencing this and I can see that in your screenshots, but it makes it hard for me to fix if I can't trigger the heisenbug :/

![Screenshot_2019-07-25_22-21-49](https://user-images.githubusercontent.com/2107894/61877869-d5163380-af2a-11e9-8b83-38fd91e9f60c.png)

**Comment by MassHesteria** [comment]
Perhaps it is a Windows specific issue? I am at work now but will try running the 240p test suite tonight with side-by-side versions of bsnes to see if I notice anything.

**Comment by MassHesteria** [comment]
So I tried the 240p test suite (v1.0.3), and it shows the problem extensively. The main menu as well as quite a few of the test patterns. Disabling Fast PPU resolves the issue just like in SM. 

![test-suite-107r3-vs-107r5](https://user-images.githubusercontent.com/1452105/61919370-fb33d780-af1a-11e9-8c2b-d35c685dc6eb.png)

**Comment by Screwtapello** [comment]
I confess I didn't try with the fast PPU, and I'm not going to be near my home PC in the near future.

Did you compile bsnes yourself? Can you compile it with `build=debug` or `build=stable` and see if that makes a difference? I mean, something like:

    make -C bsnes -j5 build=debug

...instead of just:

    make -C bsnes -j5

...or however you normally build bsnes.

**Comment by MassHesteria** [comment]
I do compile bsnes myself, and that's a good idea to switch up the build configuration. Now it gets interesting...

I tried different build configurations on two revisions that have shown the issue. As I stated earlier, the first revision that shows the issue is 107r5. When I rebuild that revision in "debug" or "stable" and use the Fast PPU, bsnes crashes at the point that it would draw the background. This means the start screen for SM works fine, but bsnes crashes when Samus loads up on the planet. The 240p Test Suite crashes immediately because it must be using the same background drawing code in its menu.

When using the latest revision 107r15, bsnes does not crash in "debug" or "stable" but the drawing issue still occurs. 

Using normal PPU resolves all issues in both as expected.

**Comment by byuu** [comment]
krom confirmed this as well, and I confirmed it doesn't happen on macOS. Most likely we're dealing with an internal compiler error that only affects MinGW.

**Comment by MassHesteria** [comment]
Honestly, I small part of me is just happy that someone else sees it. Now we can get down to finding it. I'm gonna try to find where my 107r5 revision is crashing this weekend and see if that gives us any clues.

**Comment by byuu** [comment]
I fixed it. The tilecache wasn't initialized at startup. We may want to test this more with loading and unloading multiple games, especially with soft reset, but for now, it gets rid of the obvious glaring issue.
