### ISSUE TITLE
Contra III map shows graphical errors when using HD Mode 7 with supersampling

### ISSUE THREAD

**Issue by MisaelK** [byuu/bsnes#181]
When raising the Mode 7 resolution from 240p to anything higher, nothing is wrong. But with supersampling enabled, some parts seem to shift to the left. The "Choose your starting point" text disappears, and part of the background shrinks and moves to the left.

https://streamable.com/xm7e7

I tested this on bsnes v110, v111r10 and bsnes-hd beta9. Only bsnes shows this problem.

(The supersampling effect looks very different on bsnes and bsnes-hd, though. On bsnes it looks like downsampling, and on bsnes-hd it looks like antialiasing.)

**Comment by Screwtapello** [comment]
Confirmed by #156, I guess.

**Comment by Max833** [comment]
You'll find **a lot** of these glitches when you play more games with > 480p and supersampling enabled.

**Comment by byuu** [comment]
This cannot be fixed, sorry. My implementation of supersampling is not compatible with games that use EXTBG mode. It tries to blend the generated HD mode 7 full resolution scanlines down to supersampled scanlines, and then along comes EXTBG mode that renders sprites onto the supersampled BG1 and regular sprites which get trampled.

The only thing I can do is disable supersampling in EXTBG mode 7 games. I'll add this to the next WIP.
