### ISSUE TITLE
Olivia no Mystery (Japan) - black lines [v111.10]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#182]
Right before the first screen transition I can see black lines. I couldn't see them on hardware (maybe again because of my TV/SNES?).

Rewind is disabled.

https://streamable.com/geqby

![image](https://user-images.githubusercontent.com/53529402/67133631-fe82ea80-f20d-11e9-8df9-13c2f21910f9.png)

**Comment by jjfmz42015** [comment]
Do u have scanlines enabled?

**Comment by byuu** [comment]
It's your setup.

![Screenshot_2019-10-22_12-38-38](https://user-images.githubusercontent.com/2107894/67257837-d83ca380-f4c8-11e9-85b8-4b821acd1616.png)

**Comment by Max833** [comment]
@byuu: Oh, I could see it because I disabled deinterlace.
