### ISSUE TITLE
Pachi-Slot Monogatari - PAL Kougyou Special (Japan) doesn't boot

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#185]

**Comment by byuu** [comment]
This sounds familiar for some reason, I'll look into it later.
Does this mean we're up to P in the game list? :D
Starting to get excited here!

**Comment by Max833** [comment]
Maybe you've read about this game on nesdev.com:
https://forums.nesdev.com/viewtopic.php?f=12&t=17610

And yes, I'm up to P now. It's still quite a lot though. I've played 2000 out of 3600 games. So... 1600 more and then I'll finally stop bothering you. :D :P

**Comment by jjfmz42015** [comment]
@Max833 then back to A for possible regression checks lmao

**Comment by byuu** [comment]
Added missing generic SA1 without RAM board mapping, thanks.

![Screenshot_2019-10-22_12-33-53](https://user-images.githubusercontent.com/2107894/67257766-6a907780-f4c8-11e9-8316-f194213f50dd.png)
