### ISSUE TITLE
Pro Yakyuu Nettou Puzzle Stadium (Japan) doesn't boot

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#186]

**Comment by byuu** [comment]
I take it you're once again running the beta. The release version runs normally.

![Screenshot_2019-10-22_12-29-52](https://user-images.githubusercontent.com/2107894/67257568-9c550e80-f4c7-11e9-9419-0e9bf81da5d6.png)

**Comment by Max833** [comment]
Do you know what happened? I overclocked the CPU to 101% (!) and then it doesn't start >_>. Sorry.
