### ISSUE TITLE
Game flicker In Retroarch while paused.

### ISSUE THREAD

**Issue by Testsr** [byuu/bsnes#187]
Video proof is at the [Link.](https://youtu.be/OiB_80Z6QA4)

**Comment by Screwtapello** [comment]
bsnes generates video frames in xRGB1555 format. RetroArch lists xRGB1555 as a supported format, but it's a bit buggy as you've described. RetroArch are working on fixing that problem right now: https://github.com/libretro/RetroArch/pull/9629
