### ISSUE TITLE
Compile Guide

### ISSUE THREAD

**Issue by rdanbrook** [byuu/bsnes#19]
First of all, great emulator.

I think the project (as well as higan) would benefit from a simple compile guide that the uninitiated can easily follow, maybe just as a few extra lines in the README. A list of dependencies and the proper make arguments would help out a lot. I built from source this morning and had to do a little digging before I figured it out, and also had to install some libraries one by one until I could build successfully.

It has been awhile since I used standalone bsnes or higan, so another thing I'll bring up is the performance vs accuracy profiles. Is that now controlled solely via runtime options vs separate builds?

**Comment by byuu** [comment]
Are the Cirrus CI automated builds not sufficient? They're available for every OS.
For Windows: install MSYS + GCC8. Then for all systems, follow the .cirrus.yml file.

**Comment by rdanbrook** [comment]
I don't do Windows.

I looked at the .cirrus.yml just now, it does indeed have the full list of dependencies and everything I need. It wasn't obviously apparent. Thanks for pointing that out. I suppose since there are no options for performance/accuracy in there, that answers my other question.

**Comment by Screwtapello** [comment]
The higan docs have [a section on compilation instructions](https://higan.readthedocs.io/en/stable/install/linux/), which is more optimised for humans to understand... but of course, it's not actually tested regularly. The CI intsructions are tested on every push, so they should be a more reliable.
