### ISSUE TITLE
Run-Ahead and CPU Overclocking breaks MSU1 patches

### ISSUE THREAD

**Issue by bajolzas** [byuu/bsnes#190]
Running a MSU1 patched game with CPU overclock speeds up the music in the same amount as the overclock rate.
Using Run-Ahead makes the musig lag (for the lack of a better word).

Also kind of related, is there no way to use music patches without filling my game folder with pcm/msu files?

**Comment by byuu** [comment]
Fixed, thanks.

And no there is not.
