### ISSUE TITLE
Skip run ahead when it is not necessary

### ISSUE THREAD

**Issue by mkwong98** [byuu/bsnes#191]
What run ahead is doing, is taking the current input back a few frames and rerun those frames again. So if the input hasn't changed, rerunning becomes unnecessary.

**Comment by Screwtapello** [comment]
Yes, if the input has changed, rerunning is unnecessary. However, why is that an improvement?

Let's say you have runahead set to 1 frame. Under the current system, bsnes emulates every frame twice, with all the extra CPU load and power-cost that implies. If bsnes skipped runahead when the input hasn't changed, then it would mostly run each frame once, except whenever you press or release a button in which case the CPU load and power-cost would leap back up again.

Actually, it's a bit more complex than that. Currently, when bsnes emulates runahead frames, it disables graphics rendering and a few other things, so runahead of 1 frame is a lot cheaper than running two complete SNES emulators. But if we wanted to re-use previously emulated frames, we would always have to do full emulation just-in-case we needed them later. So skipping runahead when input hasn't change might actually be *more* expensive overall, depending on how often the user presses buttons.

**Comment by byuu** [comment]
In the end it may well save power, but it will be really jarring if your PC can't handle it and audio cuts out after every key press.

**Comment by bajolzas** [comment]
Kind of related, by why do we need to run the emulator "3 times" for a run-ahead of 2, (and 4 for 3 and so on)? couldn't it just run a single emulation, but two frames in the future instead of one?

**Comment by Screwtapello** [comment]
At time t=0, the user presses a button.

bsnes emulates frame 0, then emulates frames 1 and 2, and draws 2 to the screen. Frame 2 is "two frames since the button was pressed", or run-ahead=2.

At time t=1, the user releases the button.

If bsnes just continued from frame 2 to emulate frame 3 and draw it, then frame 3 is "zero frames since the button was released", or run-ahead=0.

Instead, bsnes rewinds to the beginning of frame 1, and re-emulates it with the button released, and then emulates framse 2 and 3. Frame 3 is now "two frames since the button was released", or run-ahead=2.

**Comment by mkwong98** [comment]
>But if we wanted to re-use previously emulated frames, we would always have to do full emulation just-in-case we needed them later. So skipping runahead when input hasn't change might actually be _more_ expensive overall, depending on how often the user presses buttons.

This is not true because in the current run ahead model, the save states which the emulator loads at the end of every frame are generated when the output is already disabled. The extra cost I can think of is that when run ahead is set to more then one frame, some save states are not valid anymore after a input change and need to be generated again during the rerun.

>In the end it may well save power, but it will be really jarring if your PC can't handle it and audio cuts out after every key press.

I'm not talking about PCs which can't handle run ahead to begin with. I'm talking about leaving more  CPU time to the OS to run some other processes.

**Comment by byuu** [comment]
I understand the issue in full, it's a difficult decision and I will think about it.

**Comment by byuu** [comment]
I thought about it, and I feel it's not a good idea. It gives a false impression of system requirements and creates a very unstable power usage graph that is likely to interfere with audio buffering (dynamic rate control), adaptive sync, etc. I don't want to make this change, sorry.
