### ISSUE TITLE
Uniracers, 2P & VS mode, second player bug [bsnes v112]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#193]
> When playing a 2 player game, the second player is hovering above the track even when not moving.

bsnes v112 has the same problem.

**Context:**  
https://github.com/MiSTer-devel/SNES_MiSTer/issues/26

**Fixed by:** 
https://github.com/MiSTer-devel/SNES_MiSTer/issues/69
and
https://github.com/MiSTer-devel/SNES_MiSTer/pull/44

**More information:**
https://forums.nesdev.com/viewtopic.php?f=12&t=18447
and
https://forums.nesdev.com/viewtopic.php?f=12&t=18658&p=240657#p240707

> During sprite evaluation the OAM address is being changed. Writes at
> that time will go to both OAM and High OAM.
> 
> OBJ_RANGE scans through OAM and saves in-range sprite indexes to an
> index array.
> 
> OBJ_TIME stores the sprite index to be fetched to OBJ_TIME_INDEX. This
> index is not changed unless a new sprite is fetched. It uses the index
> to read sprite data from OAM.

![image](https://user-images.githubusercontent.com/53529402/67618725-785d3a00-f7f3-11e9-9e64-6f0d4592cd87.png)

![image](https://user-images.githubusercontent.com/53529402/67618808-3d0f3b00-f7f4-11e9-87db-69fcae5fa218.png)

**Comment by byuu** [comment]
Fixed thanks.
