### ISSUE TITLE
 Contra III - The Alien Wars (USA) - invisible head

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#194]
"Fast PPU on" works fine, but with "Fast PPU off" it looks like this:

https://streamable.com/16w54
![image](https://user-images.githubusercontent.com/53529402/67619410-bb231000-f7fb-11e9-8841-eb9770891bbd.png)

Settings:
![image](https://user-images.githubusercontent.com/53529402/67619371-3801ba00-f7fb-11e9-995a-b8df18d9b98f.png)
![image](https://user-images.githubusercontent.com/53529402/67619372-3b954100-f7fb-11e9-81fc-bc746accc6e9.png)
![image](https://user-images.githubusercontent.com/53529402/67619374-40f28b80-f7fb-11e9-8577-38f406950a5b.png)

**Comment by byuu** [comment]
Fixed thanks.
