### ISSUE TITLE
marvelous 

### ISSUE THREAD

**Issue by setthh** [byuu/bsnes#195]
hello. i'm a big fan of your emulator and i want to ask a question. i was playing marvelous and there is a difference with the way text is displayed. snes9x it's really sharp but bsnes looks a little bit blurry. is this fixable?

**Comment by byuu** [comment]
You can disable the hires blur emulation for that.
You either get sharp text or proper blending in Kirby's Dream Land 3 / Jurassic Park.
Real hardware acts like the latter, so that's what bsnes does out of the box.

**Comment by Max833** [comment]
@byuu: I've played the first minutes of the game and hires blur emulation doesn't seems to be the issue. It looks fine with accuracy mode (with and without hires blur), but I can't get it that sharp with Fast mode.

Fast PPU on and hires blur emulation off or on:
![image](https://user-images.githubusercontent.com/53529402/67631650-764db680-f899-11e9-9abd-46ad72485647.png)

Fast PPU off and hires blur emulation off or on:
![image](https://user-images.githubusercontent.com/53529402/67631688-d9d7e400-f899-11e9-822d-ce2474f19c14.png)
