### ISSUE TITLE
Use MSU1 tracks from inside zip/7z file

### ISSUE THREAD

**Issue by bajolzas** [byuu/bsnes#198]
related to what was asked at the end of #190
bsnes supports running games from zip/7z files; what I wanted was to bsnes to detect the pcm/msu files inside the compressed folder and use them.
I've tried to do this with zip and the game would not detect those files, and with 7z, bsnes would not run the game at all (even though it would if I just compressed the game rom alone)

**Comment by Kawa-oneechan** [comment]
If I remember a conversation from what feels like years back correctly, MSU1 tracks are generally too large to load as a whole. They'd have to be extracted first at any rate, be it to RAM or file, which brings its own couple issues like load times.

But what do I know, I'm just a dumb kib.

**Comment by bajolzas** [comment]
Well if it really can't be done I guess being able to make a Path for these file would do

**Comment by Kawa-oneechan** [comment]
Like a single specific location to load them from? I'm not up-to-date on naming schemes but I'm not sure if that's safe when two or more games are involved.

**Comment by Alcaro** [comment]
It's possible to make a .zip extractor that returns a kilobyte at the time, which is perfectly sufficient for the music tracks.

The data track would be trickier, but you can decompress the thing while saving the decompressor state every 4MB; DEFLATE extractor state is 32KB plus some smaller stuff, so this would be about 32-40MB for a 4GB data file. A seek will jump to the closest saved state, then decompress and discard everything until the exact position.

I don't know about 7z and LZMA.

Nor do I know if this is a good idea. I'm not sure if byuu's deflate extractor can process partial input, and even if it can, it's a lot of tricky code for a fairly rare usecase.

**Comment by bajolzas** [comment]
> Like a single specific location to load them from? I'm not up-to-date on naming schemes but I'm not sure if that's safe when two or more games are involved.

Yeah, in "Settings" there is a category called "Paths",and you can choose a folder for games, patches, saves, cheats, states or screenshots.

I dont see why it wouldn't be safe, all this paths are used for all games

**Comment by byuu** [comment]
If you want to group your MSU1 music files with your games, use game paks, it's what they were designed for. If you want the data compressed more for storage space, enable NTFS folder compression on the games.

Sorry, but bsnes is complicated enough, there's already two very different ways of playing MSU1 games that covers 99% of use cases. I don't want to add a third and burden both sd2snes and Snes9X with games being stored in this new format.

**Comment by bajolzas** [comment]
My issue was not really about compression, but not filling my game's folder with pcm files, or create a folder per game (wich, if I understand right, is what gamepaks do).

I still think that having a Path in the Settings for these files, like there is for games, patches, saves, cheats, states or screenshots, would not bring that much complexity, but what do I know...
