### ISSUE TITLE
Audio popping in Shin Megami Tensei (Japan)

### ISSUE THREAD

**Issue by Sandvichero** [byuu/bsnes#199]
There is some audio crackling/popping in both the English translation romhack and original Japanese ROM of the first Shin Megami Tensei game. It is most noticeable with the music that plays in the red maze at the start of the game. Tested all audio drivers and latency options, none of them fixed the issue.

**Comment by FitzRoyX** [comment]
This game crackles on every emulator and is almost certainly not a bug. The average fidelity of tv speakers in the 90s is not what it is today, so plenty of games exhibit lazy sound programming errors like this on some or all tracks.

**Comment by byuu** [comment]
Thank you for confirming, I'll leave this open for a bug so I remember to add it to my known real hardware issues list.
