### ISSUE TITLE
Fire Emblem Thracia 776 - English patch not working

### ISSUE THREAD

**Issue by bajolzas** [byuu/bsnes#20]
The new Fire Emblem Thracia 776 english patch (ProjectExile) is not working in bsnes.
In 107.1 it shows a black screen, and on 107.17 the emulator just closes.
The patch's readme mentions an XML file to use with bsnes, but it doesnt seem to have any use (maybe they meant the older bsnes/higan).

**Comment by byuu** [comment]
It's not supported in 107.1, but it shouldn't just close in 107.17 ...

**Comment by byuu** [comment]
[fe776.log](https://github.com/byuu/bsnes/files/3438636/fe776.log)

I fixed the heuristic detection so it maps properly now, but this fan translation is broken and jumps into uninitialized RAM. I don't know how this runs anywhere else, but it doesn't really matter. The fan translators need to update their patch to not jump into uninitialized memory, sorry.
