### ISSUE TITLE
Splitscreen test does not work on latest build

### ISSUE THREAD

**Issue by Molive-0** [byuu/bsnes#200]
EDIT: see comment

The splitscreen demo (linked) shows up mildly fine on a windows build of bsnes, but shows up very wrong on a Linux build.
Here is screen shots of the windows version followed by the Linux version:
![image](https://user-images.githubusercontent.com/23285288/67643755-aedda680-f912-11e9-9b74-4d6e16b10f96.png)
![image](https://user-images.githubusercontent.com/23285288/67643760-bac96880-f912-11e9-8377-5d55eaf537ea.png)
It may have something to do with HDMA but to be frank I'm not quite sure.

Thanks
Molive

**Comment by Molive-0** [comment]
[SplitScreen.zip](https://github.com/byuu/bsnes/files/3776593/SplitScreen.zip)

**Comment by Molive-0** [comment]
Strike that original comment, turns out it's a bug with the latest version of bsnes. Here is it not working on windows:
![image](https://user-images.githubusercontent.com/23285288/67644181-fbc37c00-f916-11e9-8fcc-5ff3baeb3512.png)

**Comment by Molive-0** [comment]
Unfortunatly there's no way currently to test that this properly works without actually looking at the test - the snes program itself does not know if it is working or not

**Comment by Alcaro** [comment]
Can confirm this ROM renders badly per your pic on Linux. Flickers quite terribly too.

Turning off fast PPU is a slight improvement.
![Screenshot at 2019-10-28 01-10-10](https://user-images.githubusercontent.com/5085186/67644226-d850ff00-f91f-11e9-8c2b-172523032bbd.png)

I think ROMs can detect rendering by reading from CGRAM during active display. IIRC, it returns the pixel currently being rendered.

**Comment by Molive-0** [comment]
Exhibiting exactly the same behaviour with fast PPU off on windows

**Comment by byuu** [comment]
I don't support homebrew, sorry.
