### ISSUE TITLE
 A single request

### ISSUE THREAD

**Issue by dml360** [byuu/bsnes#201]
An option in the menus that makes the game start in full screen without the need for alt + enter

**Comment by Screwtapello** [comment]
The reason bsnes *doesn't* have a "full screen" menu option is that you need to press the "toggle full-screen" hotkey to *leave* full screen mode. If you can press it to enter full screen, that proves you know how to get back out. If you could get into full screen mode via a menu option, people might get trapped if they didn't know the right hotkey, or if a hotkey wasn't configured.

However, there was a discussion on Discord today about making Escape a universal "get out" button, to disable full-screen mode and mouse-capture and dismiss dialogs and such. If that gets implemented, having a "start in full-screen" mode would make more sense.

**Comment by dml360** [comment]
I understand, that the DEL exit key would be interesting, usually I use it as EXIT to close the emulator, anyway thanks for the answer

**Comment by byuu** [comment]
I'll consider escape to exit fullscreen plus release the mouse.
