### ISSUE TITLE
Sound Novel Tsukuru (SHVC-ZSNJ-JPN) doesn't boot

### ISSUE THREAD

**Issue by FitzRoyX** [byuu/bsnes#203]
Note: cartridge is slotted for satellaview media carts

**Comment by byuu** [comment]
Seeing as you're one of the extremely few people who can, could you try to locate which WIP (or barring that, which release) regressions occur it? It saves me a whole bunch of time.

**Comment by byuu** [comment]
There were two issues: a missing BSC-1A7M-10 entry, and an incorrect masking on BSC-1AxM-xx entries (which also affected Derby Stallion '96 and RPG Tsukuru 2.) Both are fixed.

**Comment by Max833** [comment]
As a side note: I didn't test satellaview games or games who need special controller yet (except Mario Paint).
