### ISSUE TITLE
Fast PPU renders mosaic incorrectly

### ISSUE THREAD

**Issue by FitzRoyX** [byuu/bsnes#204]
Affects commercial games, but test rom is easier to trigger and see
[mosaic+hires_(by ladida).zip](https://github.com/byuu/bsnes/files/3795004/mosaic%2Bhires_.by.ladida.zip)

**Comment by byuu** [comment]
It's as good as it's going to get for the fast PPU.

**Comment by FitzRoyX** [comment]
Would've never guessed it was speed related since it doesn't occur in snes9x

**Comment by byuu** [comment]
Thanks for the input.
