### ISSUE TITLE
Sakurai Shouichi no Jankiryuu Mahjong Hisshouhou - black lines [bsnes v112.7]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#206]
Choose the first option. Right before the text box appears, I can see black lines. It's not on my real snes and a mister Discord member (classic gaming) verified this as well.

![image](https://user-images.githubusercontent.com/53529402/68021657-60c5fb80-fca2-11e9-865a-c4edd2ac1936.png)

![image](https://user-images.githubusercontent.com/53529402/68020448-c912de00-fc9e-11e9-87fd-2873c71524dd.png)

**Comment by James-F2** [comment]
It's only for 1 frame.. on the real snes too.
Can be closed.
