### ISSUE TITLE
Shin Ikkakusenkin (Japan) - sound problem

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#210]
That's the first sound problem I have with accuracy mode.

bsnes (fast DSP on **and** off), higan v106, Snes9x and Mesen-S:
https://streamable.com/uwrjd (0:42)

hardware:
https://streamable.com/gt4zs

**Comment by byuu** [comment]
The audio volume is way too low and I can't tell what's wrong. Can you try with the randomization disabled as well? If it's still there, I need better samples of the issue please.

**Comment by Max833** [comment]
> Can you try with the randomization disabled as well? If it's still there, I need better samples of the issue please.

Yes, it's still there. I hope that's better: 

hardware:
https://streamable.com/13rcw 

bsnes:
https://streamable.com/1ix4e
As soon as the horse race starts, there is a permanent background noise.

**Comment by byuu** [comment]
I'm extremely suspicious that every emulator implementation has the exact same issue. I'm suspecting perhaps your real hardware setup is filtering out the noise, but I guess we'll see how things go. I've been wrong before.

**Comment by byuu** [comment]
I still can't tell a difference.

**Comment by SourMesen** [comment]
The buzzing once the race starts is noticeable on my end (and in the recording, too).  Playing around with the equalizer in mesen-s,  it looks like the buzzing's frequency is somewhere around 80hz.  It's not impossible that your speakers might not be able to play it too well?  I can easily imagine a laptop's speakers having problems with it (the sound is essentially only coming out from the subwoofer on my end)

Maybe some of the SNES' audio circuitry could potentially filter out that frequency? Or it might just be the TV itself, too? (I am both terrible with hardware AND audio, so...)

**Comment by Screwtapello** [comment]
I haven't tried the game in an emulator, but I can definitely hear the difference in Max's recordings. If you want to test whether your computer speakers can reliably play an 80Hz tone, you can use [an online tone generator](https://szynalski.com/tone#80,v0.75) to test with; it might also be helpful if Max can try playing an 80Hz tone through his TV to see if he can hear *that*... or try to record the sound coming directly out of the SNES, rather than being played through the TV speakers.

**Comment by byuu** [comment]
Aha, that's the issue. This Macbook speaker doesn't seem to reproduce the 80hz tone. At least not high enough to be noticeable during the game playing as well.

Yeah I am 99% sure this is there on the real hardware then and the TV (or maybe the SNES, but less likely) is filtering it out. An 80hz lowpass filter would be trivial to add, but that's probably not the right fix here.

I'll ask on Twitter.

**Comment by James-F2** [comment]
You're right, it's on the real snes too.
I could not hear that from the TV because it does not reproduce that low frequency.
![real snes](https://user-images.githubusercontent.com/31185814/68100161-3016d980-fecf-11e9-8c9e-a0909806150a.png)

Can be closed.

**Comment by byuu** [comment]
I will add it to the real game bugs documentation soon. https://byuu.net/game-bugs/snes

Thank you so much!

**Comment by Max833** [comment]
Thank you all together! I'm glad that it's just something like this. :)
