### ISSUE TITLE
drag-and-drop of games onto the main bsnes window

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#213]
It's not a big deal, but due to the fact that I play a lot of games, it's sometimes a little bit frustrating. ^^; You can't drag-and-drop ROMs where your logo is:

![a](https://user-images.githubusercontent.com/53529402/68152419-e9af9200-ff43-11e9-95ca-0b9e721db9b7.jpg)

**Comment by byuu** [comment]
Fixed thanks, will be in the next commit.

**Comment by Max833** [comment]
Thank you.
