### ISSUE TITLE
The Lost Vikings 2 (USA) - freeze [real hardware issue]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#216]
https://github.com/TASVideos/BizHawk/issues/912

> On **level 22** (password **HRDR**, video: https://youtu.be/FZ_eiiRDzZM), there is a **room with the kid** that you can reach with Scorch. He will taunt you, as always, but you must repeat the dialogue many times until Scorch will say "Oh, is that it?". You will hear a jingle, and new powers will be unlocked: Eric: can charge underwater (Y+left/right). He will be invincible while charging underwater. **Baleog: can pull himself up in the air (Y+down)**. Fang: can howl, killing all enemies on the level (Y+B). Scorch: fireballs now pass through enemies, killing them instantly. These fireballs also destroy obastacles like Eric's head bash does. Tomator's shield does not protect him from the powered-up fireballs.
![image](https://user-images.githubusercontent.com/53529402/68479908-be72be80-0233-11ea-9978-b68066f2dada.png)

I tested level 22 and the freeze looks like this as soon as you press **Y+down** with baleog:

![image](https://user-images.githubusercontent.com/53529402/68479956-da766000-0233-11ea-8003-eb6fc036cd8a.png)

I played the game with my real snes as well and..... same issue. So this freeze is hardware behaviour:

www.streamable.com/44twz

I will leave this open so you can add this to your real hardware issues list, @byuu.
[Lost Vikings 2 (USA) - bsnes save state.zip](https://github.com/byuu/bsnes/files/3824788/Lost.Vikings.2.USA.-.bsnes.save.state.zip) (**third save state**)

![image](https://user-images.githubusercontent.com/53529402/68480194-80c26580-0234-11ea-907f-30fe10974eb5.png)

**Comment by byuu** [comment]
Okay, thank you.
