### ISSUE TITLE
[Real hardware issue] Stable Star - Kyuusha Monogatari (Japan)

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#223]
Choose the first option, enter a name and from then on just press a and you will get to a screen that tremble and flicker. Here is a video: https://streamable.com/8xad7

The problem is that I don't know how it looks on real hardware, because even sd2snes doesn't boot this game. 

Every emulator shows this a little bit different though... so _something_ is going on there.

Mesen-S, Snes9x, bsnes (higan v106 does the same as bsnes): 
https://streamable.com/450kt

**Edit:** Okay, now it works (SuperCIC was disabled). On my SNES it looks like snes9x, but it's probably my TV again? @James-F2 says it looks like bsnes on his real hardware. 

Either way... it's definitely an issue with Mesen-S, @sourmesen.

![image](https://user-images.githubusercontent.com/53529402/68544367-bd23cc00-03c2-11ea-9ed5-818349d82c8d.png)

**Comment by James-F2** [comment]
That's not as 'issue' but rather a technique to create pseudo hi-res image in 240p.

**Comment by FitzRoyX** [comment]
I'm gonna guess there's an here. There's no reason why bsnes can't be as legible as snes9x.

**Comment by byuu** [comment]
That looks like interlacing rather than pseudo-hires. Try turning on the "deinterlace" option maybe?

**Comment by Max833** [comment]
It was exactly this, byuu. ^^; Looks as legible as snes9x now. Sorry!

Closed.

**Comment by FitzRoyX** [comment]
I can't match Max's results. Deinterlace stops the flickering, but that's it. I don't think snes9x has deinterlace, so I also can't explain why static text between it and bsnes with deinterlace off looks so different. Maybe this game is using interlace mode in weird ways. Maybe it warrants a closer look.

**Comment by James-F2** [comment]
The game does not enable the interlace flag on the real console.
For some reason the developers decided to create a pseudo hi-res text with consecutive frame in 240p.
