### ISSUE TITLE
[Fast PPU issue] Sugoro Quest++ - Dicenics (Japan)  - Scanline Timing [bsnes v112.10]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#224]
https://streamable.com/v8nqu **(0:21)**

![image](https://user-images.githubusercontent.com/53529402/68551366-8a9ec100-040c-11ea-8a15-9b0ad38d6011.png)

**Comment by byuu** [comment]
There's turning out to be a lot more of these than I thought. Anyway, fixed, thanks.

**Comment by Max833** [comment]
Thanks byuu. Snes9x does now the same as bsnes. :) https://github.com/snes9xgit/snes9x/issues/595
