### ISSUE TITLE
Inaccurate SA-1 timings with default settings

### ISSUE THREAD

**Issue by obunden** [byuu/bsnes#226]
I tried the SNES speed test suite v5.1 with latest bsnes git in retroarch. The default core settings gives inaccurate SA-1 timings (See images). Disabling "Coprocessor Delayed Sync" gives the same results that byuu mentions in his latest state of emulation post. (https://articles.byuu.org/state-of-emulation-v)

The bsnses git standalone version has the same problem, but I couldn't find that particular option. Disabling all the fastmodes etc seemed to have the same effect tho.

Default settings:
![2019-11-16-095639_1920x1200_scrot](https://user-images.githubusercontent.com/56209614/68991006-41aa9a80-085a-11ea-86b2-ebf21b64ee45.png)

Without Coprocessor Delayed Sync:
![2019-11-16-095712_1920x1200_scrot](https://user-images.githubusercontent.com/56209614/68991008-43745e00-085a-11ea-91c0-bcffed09bf2a.png)

**Comment by byuu** [comment]
Yes, this is by design. The accurate sync only matters for doing much better on Vitor's test ROM. Games never rely on it as they pratically never share a bus, so in the same way that bsnes defaults to the faster PPU renderer, it defaults to running SA1 games faster.
