### ISSUE TITLE
Green lines on the "overscan" in Jurassic Park (USA) (Rev 1)

### ISSUE THREAD

**Issue by obunden** [byuu/bsnes#228]
See https://github.com/byuu/higan/issues/61

**Comment by byuu** [comment]
I don't really feel the bug needs to be in two places, but since you already submitted it, I guess it's fine.

**Comment by obunden** [comment]
I mostly added it to get more eyes on the issue to see if anyone else can reproduce it. Since both are affected but behaves slightly different I thought it warranted a separate entry. I don't know how much of the code is shared between bsnes/higan to be honest. Feel free to close it if you feel that is better to keep everything at one place.

**Comment by byuu** [comment]
Fixed in v112.11
