### ISSUE TITLE
Cannot set special characters for input mapping

### ISSUE THREAD

**Issue by gnaghi** [byuu/bsnes#230]
On bsnes Linux, in settings/Input, it is impossible to choose a «special» keyboard character for any mapping.
By «special», I mean characters like é ç è.
Tested on Ubuntu 18.04, bépo layout.

**Comment by byuu** [comment]
That one's going to be way beyond my abilities, I'm afraid.

My hardware abstraction layer for each keyboard input API (RawInput on Windows, Carbon or Quartz on macOS, SDL or Xlib on Linux and BSD) has to have string names and ID codes associated with every keyboard key.

As such, I only have the typical ANSI character keys defined.

Capturing all other types of symbols would require someone with said keyboards to add the mappings to every single keyboard driver. Doing that for every language would be impossible.

So I'm afraid this is a can't fix, unless someone with a *lot* of free time comes along, sorry.

**Comment by Screwtapello** [comment]
My understanding is that keyboards generally all have the same ID codes, but they differ in terms of what string is generated when you press a key. So, scancode 0x16 might be "s" in the traditional US English layout, but "o" in Dvorak. A library like ruby shouldn't care what string is generated, so it's reasonable to have some hard-coded human-readable defaults (like 0x16 → "s") and map everything else to an auto-generated string like "scancode:0x16". Then ruby would work for every possible key in every possible layout, with the only disadvantage being that some keys would have unhelpful names... but that's better than having them silently do nothing.
