### ISSUE TITLE
BSNES GamePak loading issues

### ISSUE THREAD

**Issue by Phillip-May** [byuu/bsnes#233]
I know higan and gamepaks are currently in an experimental phase and I'm one of the few people that tries to use them. I would just like to point out that gamepaks with manifests generated with release higan v106 don't work out of the box in bsnes 112.

In addition I tried usually the nightly build of icarus to generate a newer manifest file and even this did not work out of the box in bsnes requiring an extra identical copy of the firmware. 
Instead of needing one copy of the firmware like in release higan:
dps1b.program.rom
dps1b.data.rom

It needs two copies for some reason
dps1b.program.rom
dps1b.data.rom

upd7725.data.rom
upd7725.program.rom

and deleting either causes the game to boot to a black screen.
Including none of the files causes it to fall back to HLE.

However after all my attempts the game does work with LLE in bsnes so I hope this information is useful to anyone else who tries to use the gamepak format.

Tested on bsnes version 112.

**Comment by byuu** [comment]
That is very unusual, I'm sure I didn't have both in my gamepaks on my system, but maybe it pulled some from my local home folder. I'll look into it, thank you.

But yes, the manifest format changes from release to release, and higan v106 is two years old already =(

**Comment by byuu** [comment]
I fixed it, I was trying to read upd7725.(program,data).rom whereas icarus was using dsp(1,1b,2,3,4).(program,data).rom. I've kind of gone back and forth on which one I want to support, but for the sake of expedience I'll support what higan v106 used in bsnes so your games will work for now.

I'll try to eventually support both.
