### ISSUE TITLE
Nitpick - Bahamut Lagoon screenshot "Temporally Play"

### ISSUE THREAD

**Issue by apollolux** [byuu/bsnes#235]
Hey dude! I don't know if it's actually like that in the JP version or if it's because of an English translation patch, but that "Temporally Play" is bugging me and I'm sure you've probably heard a thing or two from the bBoards and/or Twitter about it. If it's a patch and you're able to modify it, please consider having it be "Temporarily" instead of "Temporally" if that's the more likely word, or if it's meant to be a "Continue" or "Resume" from a temporary in-memory autosave then that also might make more sense. If not, please feel free to close this at your leisure.

Keep on rocking, dude!

**Comment by Screwtapello** [comment]
I asked byuu about that once and he said that's a screenshot of the unmodified JP version.

**Comment by byuu** [comment]
It's part of the original game, yeah. I'm not going to doctor the screenshot, sorry :p
