### ISSUE TITLE
(Request) On-Screen text in Full-Screen

### ISSUE THREAD

**Issue by xZabuzax** [byuu/bsnes#238]
Bsnes is a pretty damn good emulator, we all know that but IMHO its still lacking some basic functions that other emulators have and one of those functions is On-Screen text.

It would be nice having that feature so we could see which Save State slots we have selected while we are in Full-Screen because returning to Windowed mode to see which Save State slot we selected is not fun and honestly, it's quite a turn off for some users.

Thanks.

**Comment by byuu** [comment]
It's displayed in the status bar. I don't put text into the video stream for fullscreen mode because it's really complicated. My resolution scales up to 4K whereas other emulators are only 256x224 to 512x448. If I just draw a bitmap font, it won't look good. A vectorized font will require additional libraries that complicate compilation.

**Comment by xZabuzax** [comment]
I see, that's a shame. Snes9x and Mesen-S have those features and IMHO features like that makes an emulator more eye-candy for people like me, oh well, I respect your decision for not implementing that feature.

Hopefully you can reconsider it and find a way to implement it in Bsnes in the future. I guess this threat served its purpose, you can close it if you like dude.

**Comment by byuu** [comment]
Snes9X and Mesen-S do not have HD mode 7.

It's a nice feature to add, but HD mode 7 makes it far more difficult.

**Comment by xZabuzax** [comment]
> Snes9X and Mesen-S do not have HD mode 7.
> 
> It's a nice feature to add, but HD mode 7 makes it far more difficult. I'll do what I can, but no promises.

That's correct, those emulators doesn't have some features that Bsnes have like HD mode 7 so Bsnes gets some points there too. It's just a shame that those cool features are on different emulators, I want Bsnes to have all the cool features from the other emulators because I want to make Bsnes my default Snes emulator.

I'll cross my fingers hoping that you reconsider this feature but don't force yourself if you really don't want to. I thought that feature was easy to implement but for the looks of it that feature is going to be difficult.

**Comment by byuu** [comment]
Okay, thanks.
