### ISSUE TITLE
Nightly build issues (macOS, Linux, BSD)

### ISSUE THREAD

**Issue by byuu** [byuu/bsnes#24]
macOS: nightlies are missing the +x executable mode bit, so they do not run.

Linux: at least on Arch, Super Air Diver 2 is crashing the emulator when HD mode 7 is enabled. Building the binaries directly on the target system avoids this.

macOS, Linux, BSD: we need to disable -march=native for the nightly builds. It's a nice speed boost, so maybe put it behind a compile-time flag, but I'd like to not have to manually type out "make native=true" every compile, so maybe check an environment variable or something too, hmm.

**Comment by Screwtapello** [comment]
The changes in byuu/higan#16 should fix the "executable bit not set" issue on macOS and other platforms.

I wonder if the Super Air Diver 2 crash is also a `-march=native` problem, if it only occurs in a particular situation and rebuilding the code locally fixes it.

**Comment by byuu** [comment]
Fixed, thank you!
