### ISSUE TITLE
(libretro) SGB saves missing game filename

### ISSUE THREAD

**Issue by dobyrch** [byuu/bsnes#240]
When running a Super Game Boy game with RetroArch, the save is written to a file named `.srm` (just an extension with no name).

It also reads the save from the same file, so everything will work as expected... until you try playing a different game, which will overwrite the previous save.

**Comment by Max833** [comment]
Hi. You should report this here: https://github.com/libretro/bsnes

**Comment by dobyrch** [comment]
Will do, thanks.

Closing.
