### ISSUE TITLE
Support Large Cx4 ROMs

### ISSUE THREAD

**Issue by Awakened0** [byuu/bsnes#241]
[According to this](https://www.romhacking.net/forum/index.php?topic=11130.msg382411#msg382411) there were some posts on the old byuu boards about adding support for larger ROMs; specifically to get the Mega Man X3 [Zero Project](https://www.romhacking.net/hacks/4086/) hack working. But it still freezes on a black screen in the latest bsnes libretro core, so I guess it was forgotten or there was another reason for not adding support. Maybe it was only added to higan. I brought this up in an issue on Mesen-S' repo first and it sounds like it's not a hard thing to add, so I figured I'd ask about it here too.

**Comment by byuu** [comment]
You can most likely run it with a custom manifest, though the syntax is likely not identical to higan v106 (which was released two years ago.)

I don't really have any plans to continue supporting custom board definitions. I made exceptions for ExLoROM and the Tengai Makyou Zero fan translations though, so you never know.

**Comment by byuu** [comment]
Seems there's no interest, so I'll politely decline to support this one. I can't just keep adding board hacks for every ROM hack that wants to do things that weren't possible on real SNES game PCBs.
