### ISSUE TITLE
Super Mario Kart Item issues

### ISSUE THREAD

**Issue by Z3ddrich** [byuu/bsnes#25]
I using an older version of higan found in my linux repositories v094.  I've been trying to get Super Mario Kart to play properly, but can't seem to figure this out.  The game behavior issue I'm having is when playing after I pick up an item, I can use it over and over again(the pic at the top goes black like it should)and never pick up another item.

I've combined dsp1b.program.rom and dsp1b.data.rom into the sfc but to no avail.  I have tried multiple rom files, but with no luck.  It seems to me something is set wrong somewhere, and it's not clearing a cache properly, but I would have idea how to fix this.  Has anyone else seen this problem?

**Comment by Screwtapello** [comment]
v094 is over five years old at this point. Can you try with the new [bsnes v108](https://bsnes.byuu.org/)?

**Comment by byuu** [comment]
![2019-07-30 20 02 42](https://user-images.githubusercontent.com/2107894/62124376-07e27200-b305-11e9-868e-24f8580d1dce.jpg)

I tested it, it works fine in v108. One idea ... maybe you left a cheat code enabled in v094?

**Comment by Z3ddrich** [comment]
I never used cheats... so I wouldn't know how to enable or disable cheats even
