### ISSUE TITLE
[Accurate and fast PPU issue] Hang in "Frisky Tom" in "Nichibutsu Arcade Classics" - attract mode doesn't start [bsnes 113.1]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#252]
I've read the changelog of Mednafen and found this: 

> Hang in "Frisky Tom" in "Nichibutsu Arcade Classics
(https://forum.fobby.net/index.php?t=msg&th=1852&start=0&)

Another source with more details:

> Extended DMA NMI delay kludge to cover 8-bit LDX #imm to fix hang in "Frisky Tom" in "Nichibutsu Arcade Classics".
https://mednafen.github.io/documentation/ChangeLog.txt

I tested this and indeed.... there is a possibility that the game hangs with bsnes:

 https://streamable.com/303c9 (**00:54**)

And SNES9x... crashes completely. O_o 
Mesen-S is fine, though.

**Comment by byuu** [comment]
We'll need to test this on a couple of real hardware systems to make sure it never happens there. Just one isn't enough for things like this (see: Magical Drop, Super Bonk, Dirt Racer, etc)

**Comment by byuu** [comment]
The game is reading uninitialized memory. Disabling the entropy fixes it, so this bug will happen on certain real SNES consoles (maybe always, maybe sometimes, maybe never.)

I've added a hotfix for it, thanks.
