### ISSUE TITLE
[Fast PPU issue] Super SWIV - Scanline Timing [bsnes v113.1]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#253]
European/Japanese version of Firepower 2000 (https://github.com/byuu/bsnes/issues/115).

![image](https://user-images.githubusercontent.com/53529402/71473390-16ab5300-27d7-11ea-9a3a-5714ab8a12de.png)

**Comment by byuu** [comment]
Hiya, thanks for the report! My vacation's just wrapping up; I'll get this fixed soon.

**Comment by Max833** [comment]
Hi byuu. There's no rush. I hope you're doing well. :)

**Comment by byuu** [comment]
Fixed.
