### ISSUE TITLE
Commit 357d05 broke paths to firmware/Defaults to HLE

### ISSUE THREAD

**Issue by Pr3ttyF1y** [byuu/bsnes#255]
Commit 357d05 with the comment "Fix LLE gamepak firmware name lookups (use identifier, not architecture)" seems to have broken paths to look up firmware images on Windows. I tried moving the firmware folder from my BSNES directory, to the /roaming/bsnes directory, my rom directory, placing the firmware in the same directory as the rom (both compressed and not) and it just doesn't seem to pick up on the firmware and defaults to HLE for those coprocessors that have HLE emulation available and just gives a firmware missing error when trying to run those that don't (the Shogi games).

**Comment by byuu** [comment]
I mean I literally tested it before pushing the patch. It imports here, and I don't have a lot of bandwidth to debug why it might not be detecting for you. Any chance you can dig into the code?

**Comment by byuu** [comment]
Oh I see. You're using game ROMs and I am using gamepaks.

Okay I just reverted it then. I guess we'll go back to requiring the upd7725 filenames for gamepaks for now.
