### ISSUE TITLE
[Accurate and fast PPU issue] Tatakae Genshijin 2 - attract mode interrupts too early

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#259]
**Left**: bsnes 113.2 and higan 106

**Right**: SNES9x, Mesen-S, bsnes 0.73 and on hardware

https://streamable.com/kodzm

---------------------------------------
European and u.s. version have the same issue. It's called "**Congo's Caper**".

**Comment by byuu** [comment]
This is also caused by auto-joypad polling.

I've reduced the polling delay for this to be compatible with Taikyoku Igo - Goliath, Tatakae Genshijin 2, and Nuke (PD). We will have to do more hardware reverse engineering to emulate this accurately.

At least we have three test cases now. Thank you.
