### ISSUE TITLE
missing function that was present in beta

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#26]
The beta release was smart. User could have BNSES in fast ppu and if ASP was loaded it would auto use dot PPU.

Now user has to manually switch back and forth.

be nice to have this option back. I know not everyone like it. make it a selectable option itself under emulation?

In the terms of being less reasource hungry and user friendly it would be nice to have this option back. that way bsnes will only be dot render heavy only when needed and automatically.

PLEASE :)

**Comment by byuu** [comment]
I thought I still had that support, I must have broken it accidentally? I'll fix it.

**Comment by jjfmz42015** [comment]
Thanks very much!!

**Comment by byuu** [comment]
It's fixed, it will work correctly in the next nightly. Thanks for the report!

**Comment by jjfmz42015** [comment]
Good stuff! Thank you very much for that

**Comment by jjfmz42015** [comment]
works!
