### ISSUE TITLE
[Accurate and fast PPU issue] Tintin in Tibet (Europe) (En,Es,Sv) - doesn't start

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#260]
![image](https://user-images.githubusercontent.com/53529402/71535179-5d4a9b80-2904-11ea-8396-04c2bb20faee.png)

It works when I load the rom manual and choose PAL instead of AUTO or with higan 106.

**Comment by byuu** [comment]
Fixed, my heuristics was treating a region code of 0x12 as NTSC.

**Comment by OV2** [comment]
@byuu: while fixing this in s9x I noticed that you classify region 0x0b (ROC) as NTSC. The only rom I could find with that id was "Sangokushi III (HK)", and I always thought Hong Kong used PAL. Do you have some more information about this?
