### ISSUE TITLE
[Fast PPU issue] Winter Olympic Games - Scanline Timing [bsnes v113.3]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#263]
Black line @ 0:20.

**Affected games:** 
Winter Olympic Games - Lillehammer '94 (USA) (En,Fr,De,Es,It,Pt,Sv,No)
Winter Olympics - Lillehammer '94 (Europe) (En,Fr,De,Es,It,Pt,Sv,No)

https://streamable.com/jgtdy

![image](https://user-images.githubusercontent.com/53529402/71555697-350b8b80-2a2f-11ea-83bc-150bd2cea34c.png)

**Comment by byuu** [comment]
Yeah I remember this game, it writes to change the OAM layer mid-frame to draw the entire background as sprites. I will see if a scanline override can correct it, otherwise I'll blacklist the fast PPU for it. Thanks!

**Comment by byuu** [comment]
A scanline override doesn't work for this unfortunately. I fixed it by disabling the fast PPU for this title.
