### ISSUE TITLE
[Fast PPU issue] Wild Snake (USA) - Scanline Timing (?) [bsnes v113.3]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#264]
Garbage on the upper left corner. It's not always the same, so... I'm not sure that this is scanline timing.

**Affected games:**
Wild Snake (USA)
Super Snakey (Japan)

![image](https://user-images.githubusercontent.com/53529402/71556483-8587e680-2a39-11ea-9db9-eef002e98c54.png)

**Comment by byuu** [comment]
I'll try to adjust the scanline timings and if it doesn't work, I'll blacklist the fast PPU for this title, thanks.

**Comment by byuu** [comment]
This happens with both renderers. The game is placing extra sprites at H=0,V=0 which is cut off by most TVs. This one's just bad design. Good eye though!
