### ISSUE TITLE
[Accurate and fast PPU issue] Williams Arcade's Greatest Hits

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#265]
I didn't press anything. bsnes skips pretty much everything and starts the first game on the list.

**Affected games:**
Williams Arcade's Greatest Hits (Europe)
Williams Arcade's Greatest Hits (USA)

https://streamable.com/mpme5

**Comment by Max833** [comment]
The same happens with "World Masters Golf (Europe)"

**Comment by byuu** [comment]
Does it happen both with v113 and the latest WIP? How about with other emulators, higan v106, bsnes v073, etc? Just curious if you don't mind, I'll test it more tomorrow to see what's up, thanks.

**Comment by Max833** [comment]
It doesn't work with 113.3, but works fine with bsnes 0.73 & 113.1 and higan 106. So... it's probably because of the workaround to reduce auto-joypad polling delays?

**Comment by byuu** [comment]
Williams Arcade's Greatest Hits lets us confirm the $421x latches aren't set to 1s, but rather to 0s. I can't fix World Masters Gold unless I completely disable auto-joypad polling. Clearly the implementation is fundamentall flawed, so I'm disabling it for now until I can reverse engineer the exact behavior. I've noted all of this in the source (and all games affected) so we can keep track of this, thanks!
