### ISSUE TITLE
[Accurate and fast PPU issue] World Class Service Super Nintendo Tester (USA) [bsnes v113.3]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#266]
When overscan area is enabled, you can see a blue line at the top. I don't see this line on bsnes 0.73, higan 106, SNES9x or Mesen-S.

![image](https://user-images.githubusercontent.com/53529402/71557423-457b3080-2a46-11ea-9393-30d974231f14.png)

**Comment by byuu** [comment]
Ah this I can definitely fix, I know what's wrong just from the screenshot. Thanks.

**Comment by byuu** [comment]
Fixed for both PPU types, thank you.
