### ISSUE TITLE
[Accurate and fast PPU issue] Yuuyu no Quiz de Go! Go! (Japan) - doesn't boot [bsnes v113.3]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#267]
It works with bsnes v0.73, higan v106, Mesen-S and SNES9x 1.60 though.

**Comment by byuu** [comment]
This game stores an extra title byte, "YUYU NO QUIZ DE GO!GO!", the last ! is 0x21 in hex, which states HiROM mapping, even though it's a LoROM game. I special cased this game's title string so it detects as LoROM.
