### ISSUE TITLE
[Fast PPU issue] World Cup Striker - Scanline Timing (?) [bsnes v113.3]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#268]
Geez... I know... it's _really_ trivial. I'm sorry.

**Left:** Fast PPU
**Right:** Accurate PPU

https://streamable.com/2mj9z

**Fast PPU**
![image](https://user-images.githubusercontent.com/53529402/71561375-0664d380-2a76-11ea-870a-d5eea82490f9.png)

**Accurate PPU**
![image](https://user-images.githubusercontent.com/53529402/71561378-0e247800-2a76-11ea-8ca3-76ed279cff39.png)

**Comment by byuu** [comment]
It's not the scanline render position. I've disabled the fast PPU for this game for now.
