### ISSUE TITLE
[Accurate and fast PPU issue] Star Wars games - pause issue [bsnes v113.4]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#269]
Before I will play the last 200 games, I want to investigate ~30 games further. Super Star Wars - The Empire Strikes Back (USA) is one of them and it turns out, the issue I have noted wasn't one. But what I noticed: With version 113.4 I can't pause the game anymore.

**Affected games:**
Pretty much all Star Wars games
Return of the Jedi, The Empire Strikes Back and Super Star Wars

No problems with higan v106, SNES9x or bsnes v073.

**Comment by Max833** [comment]
And "Super Conflict" has some problems as well: https://streamable.com/lf1xi

**Comment by byuu** [comment]
Since when is input the number one problem in SNES emulation affecting half the apparent library?

**Comment by byuu** [comment]
Games that have issues with auto-joypad polling disabled:

* Super Conflict: sends random inputs even with no buttons pressed
* Super Star Wars: Start button auto-unpauses

Games that depend on the clear value of the shift registers during polling:

* Nuke (PD): inputs do not work
* Taikyoku Igo - Goliath: start button not acknowledged
* Tatakae Genshijin 2: attract sequence ends early
* Williams Arcade's Greatest Hits: inputs fire on their own
* World Masters Golf: inputs do not work at all

Looking at it from all angles, Taikyoku Igo - Goliath is the stand-out. So I've added a hack to bypass the polling for this one specific game until we can figure out the exact auto-joypad polling behavior. With that, every game listed above works now with v113.5.

Aside: I can't tell you how much I'm looking forward to you being finished with this testing ^-^;
