### ISSUE TITLE
[Fast PPU issue] Marvelous [bsnes v113.5]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#274]
Finally... I played the most recent no-intro rom set with 3626 games and reported everything, I've noticed with official games. The only thing I have to do now is to verify ~15 games on real hardware (it's about the accuracy mode). 

The last fast PPU issue that remains, is this one: https://github.com/byuu/bsnes/issues/195

> hires blur emulation doesn't seem to be the issue. It looks fine with accuracy mode (with and without hires blur), but I can't get it [text] that sharp with fast mode.

![marvelous](https://user-images.githubusercontent.com/53529402/71727209-d3d22680-2e39-11ea-9bac-6e3278b736e1.jpg)

**Comment by byuu** [comment]
Congratulations on finishing the entire No-Intro set!! :D
I can't wait until those last 15 are done and I can hopefully finally take a break ^-^;;

But yeah unfortunately this one's a known issue. It's also the cause of that one game with the fog level I had to disable the fast PPU on: a while back AWJ helped enhance the accuracy PPU to have more accurate color blending, but the accuracy PPU is so incredibly different in structure that I was never able to port the color blending modifications back to the fast PPU.

I'm not sure if we should disable the fast PPU for this one ... it will make Marvelous a lot more demanding, and it's actually a pretty decent game. The text isn't illegible, just ... worse. Unfortunately I really don't know how to fix it though. I'd need some help with porting over the accuracy PPU color blending logic.

**Comment by James-F2** [comment]
This fixed it on mister:
https://github.com/MiSTer-devel/SNES_MiSTer/pull/109/files

**Comment by Max833** [comment]
I found an old thread about this on snes9x.com. Surely not helpful to port the complete color blending modifications back to the fast PPU, but maybe enough information to add a specific hack for Marvelous? http://www.snes9x.com/phpbb3/viewtopic.php?t=5639

Commit:
https://github.com/snes9xgit/snes9x/commit/c717e7d5ef9940a7e12374d0d65ae7fefec41beb

**Comment by byuu** [comment]
For the time being, I've added an override similar to the few others we have to force the accurate PPU for this title. I'll try to look into something for a future release. I'll update the Wiki page as well in the near future to document all workarounds like this. They're also documented in the source code.
