### ISSUE TITLE
Add RetroAchievements support to Libretro core

### ISSUE THREAD

**Issue by nfp0** [byuu/bsnes#276]
All bsnes and higan cores in Retroarch, besides this one, support RetroAchievements (even higan Accuracy and nSide Balanced, contrary to the info in the docs).

It would be great to have this excellent up-to-date core also supporting RetroAchievements. Maybe code from the other bsnes/higan cores can be ported to this one to save time.

**Comment by Alcaro** [comment]
In not-RetroArch-specific terms: OP wants someone to implement [this function](https://github.com/byuu/bsnes/blob/master/bsnes/target-libretro/libretro.cpp#L648-L658).

```c++
// Currently, there is no safe/sensible way to use the memory interface without severe hackery.
// Rely on higan to load and save SRAM until there is really compelling reason not to.
RETRO_API void *retro_get_memory_data(unsigned id)
{
	return nullptr;
}

RETRO_API size_t retro_get_memory_size(unsigned id)
{
	return 0;
}
```

**Comment by byuu** [comment]
I don't have any interest at all in adding this personally, but feel free to check with the libretro port maintainers. If they send me a pull request with these functions implemented, I'll merge it.

**Comment by nfp0** [comment]
Thanks. I've asked on the libretro port if anyone can get on this.
