### ISSUE TITLE
[Accurate and fast PPU] Mosaic emulation

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#278]
I know you once said this:

> https://github.com/byuu/bsnes/issues/71 
 It's a pretty good example of our mosaic emulation not being 100% correct. Mosaic is very tricky to get right. I'll see if I can fix this without breaking all the difficult mosaic edge cases like Super Turrican and that one Sim (something) game.

And it's really hard to see a difference on hardware and bsnes, but there were two cases that could be helpful to improve this behaviour.

**Jimmy Connors Pro Tennis Tour (USA)**

Start a game and press START, the game pauses and you will see a mosaic effect. Press START again and you see that this effect goes beyond the black line. On hardware, SNES9x and Mesen-S this doesn't happen.

Hardware video: https://streamable.com/w8gya
 
![image](https://user-images.githubusercontent.com/53529402/72217302-baf9fd00-352c-11ea-893b-93f33fd73ef9.png)

bsnes v114, higan and bsnes v073:
![image](https://user-images.githubusercontent.com/53529402/72216534-82edbc80-3522-11ea-949d-00dc0b229f26.png)

**Jurassic Park Part 2 - The Chaos Continues (USA) (En,Fr,De,It)**

At the bottom there is a lot of garbage. This isn't there on hardware.

hardware video: https://streamable.com/gjjgp
 
![image](https://user-images.githubusercontent.com/53529402/72217344-f268a980-352c-11ea-8a9c-608cf9b62ae5.png)

bsnes v114, higan and bsnes v073:
![image](https://user-images.githubusercontent.com/53529402/72217098-1c6c9c80-352a-11ea-9c98-974870f01298.png)

**Edit:** One more. @SourMesen fixed this yesterday with Mesen-S.

**Final Fantasy 6**
Mosaic bugs when battle starts inside caves.

![ff6](https://user-images.githubusercontent.com/53529402/72220857-88b0c580-3555-11ea-864e-c2e105d135d3.jpg)

**Comment by byuu** [comment]
I'll just put it as help wanted. I don't think I have it in me to fix this one, I'm afraid.

**Comment by byuu** [comment]
Ah heck, meant to just hit "comment", not "close and comment", sorry.

**Comment by byuu** [comment]
I cannot reproduce the mosaic patterns in your Final Fantasy VI screenshot in spite of dozens of tries on different tiles inside the first cave.

**Comment by Max833** [comment]
Ok. I will try to make a video tomorrow.

**Comment by byuu** [comment]
I figured it out anyway. There's only a single vertical mosaic counter, not one for each background. Next WIP will fix all of these reports for both the fast and accurate PPU renderers.

https://imgur.com/a/2yqyKHD
