### ISSUE TITLE
Accurate PPU

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#279]
**Great Battle IV, The (Japan)**

At the top of the screen: line is flickering.

bsnes:
https://streamable.com/5vtdy

Hardware (there is one flickering pixel as well, though):
https://streamable.com/2v9xs
##########################################

**Septentrion (Japan)**

Flickering line.

bsnes:
https://streamable.com/7zivj

Hardware:
https://streamable.com/g9duj
##########################################

**Star Ocean**

And the last one. This is still happening: https://github.com/byuu/bsnes/issues/173 
Mesen-S has a run-ahead feature as well now (https://github.com/SourMesen/Mesen-S/commit/5f2c502be9908b80ec359d96b09688f6917b8fda) and this doesn't happen there.
##########################################

That's more of a question. Do you remember this one? https://github.com/byuu/bsnes/issues/223 It turned out that I have to enable the deinterlace function and then it's fixed. But... Mesen-S doesn't flicker at all so I assume he implemented deinterlace with the accurate mode. Is this possible with bsnes as well? Right now, just the fast PPU mode has the ability to enable this.
##########################################

By the way: I tested the whole library with the fast PPU enabled, and ~400 games with the accurate PPU, because you said pixel perfect timings isn't possilbe due to lack of logic analyzer traces and decapped analysis. So... there might be some games that aren't perfect.

Either way, thank you so much for everthing you did for the community, byuu. ^_^ I started to play games with bsnes 2011 and I always wanted to give something back and because it's really easy to report something via github... I did this. In the future, I will play with the accurate PPU so it could be possible that I find some more things and report them here. ^^ I have 1-2 interesting feature request as well... 

But yeah... that's it. 0 games left! :P

**Comment by byuu** [comment]
Deinterlace is definitely an enhancement ... I suppose it's possible to do it in bsnes, but I don't want to do it in higan. I'll think about that. The other two are pretty minor, but I'll look into them when I have some free time, maybe they'll reveal something interesting.

I really appreciate all your help, thank you so much for testing the entire library like this! :D

**Comment by Max833** [comment]
Thank you for the mosaic fix, byuu! ^_^ It's looking good, but **Power Drive** is broken again with the accurate mode now. https://github.com/byuu/bsnes/issues/217

**Comment by byuu** [comment]
Star Ocean is fixed. Forgot to serialize the probabilit estimation module of the SDD1 decompressor.

**Comment by byuu** [comment]
Fixed Power Drive again, thanks.

**Comment by byuu** [comment]
Great Battle IV is fixed.

**Comment by byuu** [comment]
Septentrion is fixed.
