### ISSUE TITLE
Periodic sound crackle in GB games via Super Game Boy in bsnes v108

### ISSUE THREAD

**Issue by xdanieldzd** [byuu/bsnes#28]
I'm experiencing some sound crackling while playing Game Boy games via the Super Game Boy emulation in bsnes v108 (Windows build, on Win 7), with a short burst of static at a regular interval, every second or so. This only occures when the game itself is currently playing sound, so not during ex. Pokemon Red or Silver's copyright screens on startup.

It does occur regardless of audio driver settings in the emulator and no matter the SGB ROM I use; it also doesn't happen in SNES games.

Maybe it's due to some mismatch or oversight in the interaction between SameBoy and bsnes, like sound buffer lengths or some such? I wouldn't know where to even start looking for that in the code, tho, so that's just a somewhat wild guess.

Attached is a short video of Pokemon Red (German version) via the Super Game Boy 2. The video part isn't important, it was just easier for me to record it all via OBS quickly.

[Zipped mp4 (bsnes108-gbcrackle.zip)](https://github.com/byuu/bsnes/files/3448062/bsnes108-gbcrackle.zip)

**Comment by byuu** [comment]
That's very likely exactly what it is, yeah. The SNES DSP and the SGB PSG both queue up samples as they're generated, and only when both have output samples do they get mixed and sent to the speaker. If they don't stay in alignment, one buffer can run out and stall out the audio. Tricky issue ... I'll mark it as a valid bug we need to fix.

**Comment by poesdelal** [comment]
Similar sound bug was fixed in standalone SameBoy v0.12.2 (14/09/2019).

**Comment by byuu** [comment]
This one was my bug after all. Sorry LIJI.

Fixed in https://github.com/byuu/bsnes/commit/e3f2e634c85ff5ebcd27edaeffac93f8da5e814a
