### ISSUE TITLE
Retroarch v114 command line aspect ratio

### ISSUE THREAD

**Issue by mibro0224** [byuu/bsnes#280]
I noticed when calling bsnes v114 libretro core from command line (launchbox or rocketlauncher), the display changes to an unexpected aspect ratio. When calling the core from Retroarch itself, there are no issues and the aspect ratio is correct. I have isolated this to only the bsnes core as I do not see it in Snes9x.

See attached images:

![IMG_0558](https://user-images.githubusercontent.com/40230382/72218556-26979680-353c-11ea-9139-76e6361c6475.jpg)

![IMG_0559](https://user-images.githubusercontent.com/40230382/72218557-2ac3b400-353c-11ea-9d76-eeb0796a817b.jpg)

**Comment by Alcaro** [comment]
I believe the solution would be to fill in [info->geometry.aspect_ratio](https://github.com/byuu/bsnes/blob/master/bsnes/target-libretro/libretro.cpp#L491).

**Comment by byuu** [comment]
@rtretiakov would you be able to send me a patch for this please?

**Comment by rtretiakov** [comment]
@byuu will take a look at it now.
