### ISSUE TITLE
blur emulation under options not working

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#29]
bllur emulation under options not working

**Comment by byuu** [comment]
For the fast PPU, blur emulation only has an effect on hires games.

**Comment by jjfmz42015** [comment]
And what about accurate ppu? Reason I ask is blur seems different in latest higan on your site.

**Comment by jjfmz42015** [comment]
> 
> 
> For the fast PPU, blur emulation only has an effect on hires games.

JUst went back to bsnes 106.44 bet blur emulation there works


my test was running ASP with dot ppu on 108.1 and on 106.44


in 106.44 blur emulation works.

in 108 and 108.1 doesnt

**Comment by byuu** [comment]
![noblur](https://user-images.githubusercontent.com/2107894/62228772-49ece000-b3f9-11e9-9cd0-75cd8ee82356.png)
![blur](https://user-images.githubusercontent.com/2107894/62228775-4d806700-b3f9-11e9-908b-220975908950.png)
I confirmed it's working in the fast PPU mode, and I just fixed it for the accurate PPU mode.

**Comment by jjfmz42015** [comment]
awesome!!


Thanks again!!
