### ISSUE TITLE
Broken Action Replay Codes in Libretro Core.

### ISSUE THREAD

**Issue by summonthethunder** [byuu/bsnes#291]
Libretro's cheat database has two kinds of cheats: Game Genie in AAAA-BBBB format and Action Replay in AAAAAABB format.  Game Genie works fine, but Action Replay does not work.

I also tried the following formats manually via the Cheat menu for RetroArch: AAAAAA:BB, AAAAAA/BB, and AAAAAA=BB.  None work.

The standalone version seems to support action replay, so it seems the libretro core should as well.

**Comment by byuu** [comment]
Hello, please check with the libretro team (rtretiakov et al) for this one. I'm not familiar with their cheat code system, but I would welcome any patches to support this.

**Comment by summonthethunder** [comment]
Hello.  I will ask the folks over at libretro.  Thank you!
