### ISSUE TITLE
Update documentation firmware folder

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#30]
I was curious if the firmware folder requirements are still the same and noticed the following when I tried to access documentation

bsnes seems to no longer ship with the following
cx4.data.rom [Mega Man X2, Mega Man X3]
sgb1.boot.rom [Super Game Boy]
sgb2.boot.rom [Super Game Boy 2]

Also does bsnes still use all of the following if present? I tried having and not having them and cant tell

cx4.data.rom [Mega Man X2, Mega Man X3]
sgb1.boot.rom [Super Game Boy]
sgb2.boot.rom [Super Game Boy 2]
dsp1.program.rom, dsp1.data.rom [Super Mario Kart, Pilotwings, etc]    dsp1b.program.rom, dsp1b.data.rom [Ballz 3D, etc]
dsp2.program.rom, dsp2.data.rom [Dungeon Master]
dsp3.program.rom, dsp3.data.rom [SD Gundam GX]
dsp4.program.rom, dsp4.data.rom [Top Gear 3000]
st010.program.rom, st010.data.rom [F1 Race of Champions II]
st011.program.rom, st011.data.rom [Hayazashi Nidan Morita Shougi]
st018.program.rom, st018.data.rom [Hayazashi Nidan Morita Shougi 2]

Thanks

**Comment by byuu** [comment]
I updated the page. Cx4 and SGB firmware was integrated, the others you still need due to them being copyrighted.

**Comment by jjfmz42015** [comment]
thank you!

**Comment by jjfmz42015** [comment]
> I updated the page. Cx4 and SGB firmware was integrated, the others you still need due to them being copyrighted.

so example. if I run Super Mari Kart with DSP1 missing the game still runs. How am I able to tell when its running using HLE or actual rom of DSP?
