### ISSUE TITLE
Using Alt-Inputs no longer working? v114

### ISSUE THREAD

**Issue by LordOfTheFat** [byuu/bsnes#303]
Coming from v108 because I began to experience a 50% drop in frames 60 to 30 for random amounts of time for seemingly no reason; hoping this build will fix that issue. But, I cannot set up alt-inputs when using my controller. 

E.g. Assigning "Up" to the d-pad "Up" and the analog stick "Up" at the same time. Furthermore, the issue is present for keyboard-strictly input or cross input. It simply defaults to Mapping #1 no matter what. 

**New to Github, hope this is an appropriate use of the issue reporting tab. Thanks in advance!

**Comment by byuu** [comment]
To map alternate inputs you need to double-click on those individual cells, not the assign button or by pressing enter.

**Comment by LordOfTheFat** [comment]
Oh geez, I feel dumb. Thank you.
