### ISSUE TITLE
Feature request. Make windows build portable by keeping BML files in bsnes root rather than users appdata

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#32]
Feature request. Make windows build portable by keeping BML files in bsnes root rather than users appdata

**Comment by byuu** [comment]
Would rather not. Every new WIP download wil lose all of your settings if I do that. If you make settings.bml yourself in the nightly WIPs it will become portable.

**Comment by Screwtapello** [comment]
Just to restate byuu's explanation more explicitly, if you want a portable Windows build:

- Download an official or nightly build
- Manually create an empty file named `settings.bml` beside `bsnes.exe`

If the empty `settings.bml` were included in the downloaded archive, then every time you upgrade bsnes, your personal `settings.bml` would be overwritten by the fresh blank one, and your settings would be lost. Apart from the initial difficulty of creating `settings.bml`, both portable and non-portable users are better off if builds do *not* include a `settings.bml` file.

I don't think there's anything more that needs to be done here, so I'll close this issue. Please re-open it if there's something we've missed.
