### ISSUE TITLE
Make it easier to turn Cheat Finder search results into cheats

### ISSUE THREAD

**Issue by Screwtapello** [byuu/bsnes#33]
Currently, the Cheat Finder is an excellent way to find memory addresses, but it's not immediately obvious how to convert a search result into something for the Cheat Editor. For example, [someone on Reddit got confused](https://www.reddit.com/r/emulation/comments/cj78nu/weekly_question_thread_20190729_to_20190804/evppj3c/).

One possibility would be:

  - when the Cheat Finder has found at least one memory location, enable a button at the bottom of the window labelled "Save" or "Add Cheat" or similar.
  - Clicking the button opens the "Add Cheat" dialog (the one from the Cheat Editor), with all the memory locations from the  Cheat Finder converted to the bsnes cheat format and added to the "Code(s)" field, and the "Name" field empty.
    - For example, if the Cheat Finder found memory address `0x123456` with value `0x78`, add `123456=78` to the "Code(s)" field
  - If the user clicks "Cancel", return to the Cheat Finder
  - If the user clicks "Add", switch to the Cheat Editor with the new cheat highlighted

**Comment by byuu** [comment]
Double-clicking a cheat finder list view entry will switch you to the cheat editor window, trigger the add cheat box, and put the code into the list box in the correct format. Maybe not the -most- intuitive, but I don't want to add another button to the already cramped bottom controls row, so this'll have to do for now.
