### ISSUE TITLE
Drop down lists take a long time to draw on Windows

### ISSUE THREAD

**Issue by Screwtapello** [byuu/bsnes#34]
Originally mentioned by @Max833 in #31:

> there seems to be a big delay with the new list-style: https://streamable.com/r1e41

To summarise the video, while switching between the various "tabs" in bsnes v108.1's Settings window on Windows 10, most widgets on each tab appear instantly, but drop-down lists (like the driver lists in the Drivers tab) flicker for a bit, or don't appear at all, for up to a second.

**Comment by byuu** [comment]
I tried, but I was unable to find a solution for this. It's a standard Windows combobox control, and all I'm doing is calling SetVisible(hwnd, true) on it. It is a mystery to me as to why it would flicker. Probably something to do with CLIPSIBLINGS/CLIPCHILDREN which have a history of causing difficulties for hiro.

**Comment by byuu** [comment]
I fixed it through a workaround. CB_SETITEMHEIGHT is just fundamentally broken on Windows. The controls now center within the requested geometry instead of resizing to fit. Not ideal but there's nothing I can do about it.
