### ISSUE TITLE
Emulation should pause when menus are opened

### ISSUE THREAD

**Issue by Screwtapello** [byuu/bsnes#35]
Originally mentioned by @Max833 in #31:

>  "pause emulation when focus is lost" is now default and that's great, but when I open "System" "Settings" "Tools" or "Help", the framerate still drops a lot. It's probably a good idea to pause emulation there, too. :)

@byuu replied:

> Yeah I'll restore pause on modality for Windows. It's nice for consistency not to pause but in practice the performance is just dreadful.

I'm not sure if this change has already been made; if it has, this issue can be closed.

**Comment by byuu** [comment]
This is done, although not personally tested. If it doesn't work we can re-open it.
