### ISSUE TITLE
Show whether special chips are using HLE or LLE

### ISSUE THREAD

**Issue by Screwtapello** [byuu/bsnes#36]
Originally described by @Max833 in #31.

bsnes *can* do low-level emulation of special chips, if the required firmware is available, but will silently fall back to high-level emulation if the firmware cannot be found. This makes it easier for people who just want to play a game, but harder for people who want to be sure they're emulating a game as accurately as possible. There's also the "Prefer HLE" option, which presumably still uses LLE (and requires firmware) for that one Shougi game without HLE support.

This is even more confusing now that some of the required firmware files are built into the bsnes binary: A user can have *no* visible firmware files, or have *all* the firmware files in the wrong place, and still get LLE in some games and HLE in others.

Once a user has loaded a game, it should be possible to find out:

  - Does this game use a special chip that has firmware?
  - If it does, is bsnes using HLE or LLE?
  - If bsnes is using HLE, is it because the "Prefer HLE" option is ticked, or because firmware could not be found?
  - If bsnes is using LLE, is it because the "Prefer HLE" option is unticked, or because no HLE is available?
  - If firmware is being used, is it internal to bsnes, or is it a file on disk? If so, what's the file path?
  - If firmware could not be found, where did bsnes look for it?

Perhaps this information could be added to the Manifest Viewer somewhere, or added as an icon to the status bar (like the "in database"/"not in database" icon) with a more descriptive tooltip (suggested by @jjfmz42015). For example:

> uPD7725, HLE (no firmware in C:\Users\st\Downloads\bsnes-nightly\Firmware)

> uPD7725, HLE (preferred, firmware in C:\Users\st\Downloads\bsnes-nightly\Firmware)

> uPD7725, LLE (firmware in C:\Users\st\Emulation\Super Famicom\smk.sfc\)

> HG51BS169, LLE (internal firmware)

**Comment by byuu** [comment]
I am defaulting to LLE since it's mostly the same speed anyway now, and if you force HLE, it will add "[HLE] " to the prefix of the game title in the emulator window. There's also a tool-tip on "Prefer HLE" to explain the option now.

**Comment by Max833** [comment]
Thanks @byuu ! One question though: I tried to start "Hayazashi Nidan Morita Shougi 2 (Japan)" with bsnes 108.5 and "Prefer HLE", but I don't see the indicator for HLE in the title bar. I mean... it's a chip with enhancement chip (ST018), right?
