### ISSUE TITLE
Add a tooltip to the "verified in DB" icon in the status bar

### ISSUE THREAD

**Issue by Screwtapello** [byuu/bsnes#37]
Currently, if I load a game that appears in bsnes' database, I get an orange icon in the bottom-left corner, and the status-bar briefly says "Verified game loaded". If I load a game that *doesn't* appear in bsnes' database, I get a purple icon and the brief message "Game loaded".

If I don't happen to notice the "Verified game loaded" message, or I don't happen to have games that appear in the database (and byuu's database is not intended to be as comprehensive as No-Intro, so there'll always be good dumps that aren't verified), it can be quite mysterious what that icon is for.

It would be nice to attach a tooltip to the icon describing what it means, like:

> This copy of the game matches the one in bsnes' preservation database, it can be accurately emulated

or

> This copy of the game cannot be found in bsnes' preservation database

**Comment by byuu** [comment]
This is done, thanks.
