### ISSUE TITLE
Support Game Genie/Pro Action Replay cheats

### ISSUE THREAD

**Issue by Screwtapello** [byuu/bsnes#39]
[On Reddit](https://www.reddit.com/r/emulation/comments/cj78nu/weekly_question_thread_20190729_to_20190804/evwps0a/), /u/legendarysnake was trying to use a Game Genie code to disable random battles in Final Fantasy 6, a code that doesn't exist in mightymo's database.

Ideally, somebody could paste GG/PAR codes into the "Add Cheat" dialog and they'd just work. Failing that, automatically converting them to the right format would be nice.

**Comment by byuu** [comment]
This is done. I also decode Game Genie / GameShark codes for the Super Game Boy, and give error messages with supported formats whenever an invalid code is entered, and I also fixed a bug with importing multi-part cheat codes from the cheat code database. A bit worrying nobody encoutered the bug in v108 yet ... hopefully people are actually using the cheat database ...
