### ISSUE TITLE
sha256 rom check

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#42]
I wanted to the test "Super Mario Kart" with LLE so I added the needed dsp rom to the firmware folder and started the game. I got graphics glitches. Turns out the rom was damaged and because of that it didn't work. Would be nice to have a error message like "incorrect sha256 checksum" or something like that when I try to start the game.

And one more question: I tried to start "Hayazashi Nidan Morita Shougi 2 (Japan)" with bsnes 108.5 and "Prefer HLE", but I don't see an indicator for HLE in the title bar. I mean... it is a game with enhancement chip (ST018), right?

![image](https://user-images.githubusercontent.com/53529402/62486201-e7139400-b7be-11e9-9976-155f93f27dee.png)

**Comment by byuu** [comment]
There's a setting to warn you when loading unverified games, but it's not a great option when I only have ~35% of the SNES library (mostly the USA set) in the database. DSP3, ST011, ST018 lack HLE implementations, so they are always LLE.

**Comment by Max833** [comment]
Perhaps I expressed myself badly, sorry. The game wasn't damaged but the dsp rom.

**Comment by byuu** [comment]
That would be a tough one ... the firmware *can* technically be anything, which is important to me. I want people to be able to make their own NEC DSP firmware code for homebrew games. Maybe I can tag the known firmware hashes to indicate their display labels (DSP1,1B,2,3,4,ST010,ST011,ST018,Cx4.) I'll reflect on it more~

**Comment by Max833** [comment]
Thank you.
