### ISSUE TITLE
commit 96c381 and later garbage on title screen of ASP!!

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#43]
commit 96c381 and later garbage on title screen of ASP!!

**Comment by Max833** [comment]
Happens with "accuracy mode" and "HLE mode", @byuu:

https://streamable.com/luvqy

**Comment by byuu** [comment]
Yeah, unfortunately these things always happen with code cleanups. I'm trying to restructure the code to be more friendly to other developers that might not be familiar with my template integer classes. I'll get this fixed, thanks.

**Comment by jjfmz42015** [comment]
@byuu I thought you were trying to be more like zsnes lol kidding

**Comment by byuu** [comment]
Fixed, thanks.

**Comment by jjfmz42015** [comment]
@byuu. No. Thank u! So happy with this emu it's a dream come true
