### ISSUE TITLE
Graphics glitches in Mario's Time Machine [USA] ingame [bsnes v108.7]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#48]
![11](https://user-images.githubusercontent.com/53529402/62578007-65943280-b8a0-11e9-8547-1d8b6957fc9d.png)

**Comment by byuu** [comment]
Yes, there's an issue with the recent commit. Let's please use one issue for this.
I'll fix it very soon, don't worry. https://github.com/byuu/bsnes/issues/43

**Comment by Max833** [comment]
I'm sorry. Wasn't sure it's the same bug. Reported games are fixed. Thank you! :)
