### ISSUE TITLE
Touching a "crash block" in Super Metroid crashes bsnes after a savestate is loaded

### ISSUE THREAD

**Issue by UNHchabo** [byuu/bsnes#50]
Some background: in Super Metroid's "Any% Glitched" speedruns, runners get out of bounds into an area of the room made up of uninitialized memory. Some of the blocks, if touched, will do various things like activate room transitions, or give you items, or deal damage. Some of them will crash the game, forcing a console reset.

If you touch a crash block on higan v106 and crash the emulated SNES, you can load a savestate and it will properly load back where you were. On bsnes v107.1 and v108, loading the savestate will cause bsnes to become unresponsive.

This unfortunately isn't easy to reproduce, but please let me know if you need more information.

**Comment by Max833** [comment]
Your savestate and a video would be a good start, I think. ^^

**Comment by UNHchabo** [comment]
Will do. I've just corrected the version numbers in my original post.

**Comment by jjfmz42015** [comment]
SO this means it crashed when trying to glitch the game?

**Comment by UNHchabo** [comment]
Correct. This speedrun finishes the game by overwriting a portion of the console's RAM to set the flag that says the escape sequence has started, then entering the ship.

So far I haven't been able to find a Crash Block to reproduce the bug. I have this video of encountering the Crash Block that caused this issue, but this video was recorded on higan, and did not use savestates:
https://www.youtube.com/watch?v=_ZgdfhScRaI&t=17m58s

Interestingly, I have had no issues loading savestates after inducing other similar-looking game-crashes that are easier to reproduce, such as shinesparking while being grabbed by a certain enemy: https://wiki.supermetroid.run/Yapping_Maw

So far the out-of-bounds crash block is the only one that's caused this bug to appear.

**Comment by byuu** [comment]
Sitting for a month with no input. I don't intend to work on this without confirmation of it being a bug, so I'm closing the issue for now. If you can demonstrate it's an actual emulation bug on real hardware, feel free to reopen.

**Comment by UNHchabo** [comment]
I was finally able to reproduce this: touching this block on v107.1 then loading a savestate causes the emulator to become unresponsive. However, on v112 this appears to be fixed, and the savestate will load as expected.

[bsnes_savestates_glitched_block.zip](https://github.com/byuu/bsnes/files/3886118/bsnes_savestates_glitched_block.zip)

I've attached a zip file with savestates demonstrating this.
