### ISSUE TITLE
bsnes should display an image of the relevant controller when mapping inputs

### ISSUE THREAD

**Issue by azoreseuropa** [byuu/bsnes#51]
What do you think? Similar:

![snes](https://user-images.githubusercontent.com/16481778/62876300-a9e55f80-bcf2-11e9-8e52-2d93616df0e9.png)

I really like it. Very nice looking.

**Comment by byuu** [comment]
I would need pictures for every supported peripheral to even consider it, including some I plan to support in the future.

**Comment by Max833** [comment]
I kinda like the minimalism design right now.  I know, it is probably not even worth mentioning, but the only thing I dislike about the configure settings is that it doesn't switch to the next hotkey automatically.

**Comment by Screwtapello** [comment]
I'm marking this "help wanted" in case somebody wants to volunteer to draw consistent diagrams of all the controllers bsnes can or might support.

**Comment by jtuc** [comment]
I think the main reason it would be nice to have an image is it's difficult to remember the layout the A/B/X/Y buttons are in (especially as Xbox controllers have reused the same letters in a different layout...)
As a stopgap, would it be possible to label the inputs as "A (right)", "B (bottom)", "X (top)" and "Y (left)" in the mapping screen?

**Comment by byuu** [comment]
I was wanting someone to make 16x16 icons that could indicate which button is which, then we could put those into the list box.

**Comment by hasas4** [comment]
I dont know if this has been said already but im on mac and it wont allow me to connect a controller to bsnes. It just wont take any inputs from my controller when ive tried to change controls. Ive closed and reopened bsnes multiple times but the issue it still happening.

**Comment by hasas4** [comment]
Oh and it takes inputs from my keyboard just not my controller. Keep up the great work!

**Comment by Screwtapello** [comment]
@hasas4 Please file a new issue, this issue is about displaying controller button images in the mapping dialog.

**Comment by byuu** [comment]
This just isn't likely. Especially if we're going to emulate more peripherals in the future, which I very much want to. Maybe one day in the future we can revisit this.
