### ISSUE TITLE
Killer Instinct (USA, Europe) (SGB Enhanced) bug

### ISSUE THREAD

**Issue by benderscruffy** [byuu/bsnes#53]
using v108.8
when you go to choose your player you are always player 2 instead of player 1
![killer](https://user-images.githubusercontent.com/2696404/63208595-a6920f80-c108-11e9-9dc6-a315b9026817.PNG)

**Comment by byuu** [comment]
Did it happen with v107 before I merged SameBoy?

**Comment by benderscruffy** [comment]
yep happens in v107

**Comment by byuu** [comment]
Should be fixed now, but not 100% certain it's entirely correct. Please let me know if it breaks the multi-player support in any other SGB games with a new issue ^-^;;
