### ISSUE TITLE
Transparent characters [bsnes v108.11][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#59]
**The Addams Family** 

Fast PPU on:
![2](https://user-images.githubusercontent.com/53529402/63504305-8d56dd80-c4d1-11e9-9d6f-4f2e337a6598.png)

Fast PPU off:
![ppu1](https://user-images.githubusercontent.com/53529402/63504211-554f9a80-c4d1-11e9-847b-5716e3011688.png)

**Ardy Lightfoot (second level)**

Fast PPU on: 
![ppu fast on](https://user-images.githubusercontent.com/53529402/63543159-6d033f00-c522-11e9-9dcb-012a82889f86.jpg)

Fast PPU off:
![ppu fast off](https://user-images.githubusercontent.com/53529402/63543162-6ecd0280-c522-11e9-92ae-1ab190cca668.jpg)

**Art of Fighting (intro, menu, sometimes ingame)**

Fast PPU on:

![1](https://user-images.githubusercontent.com/53529402/63543211-9754fc80-c522-11e9-882d-4e7ee7696bd7.jpg)

![2](https://user-images.githubusercontent.com/53529402/63543219-9a4fed00-c522-11e9-9c93-186f4599c7f5.jpg)

**Ashita no Joe**

Fast PPU on:

![as](https://user-images.githubusercontent.com/53529402/63543471-37ab2100-c523-11e9-9473-0effdf6540e0.jpg)

![as2](https://user-images.githubusercontent.com/53529402/63543478-3b3ea800-c523-11e9-8297-705b869c24d8.jpg)

**Comment by byuu** [comment]
Should be fixed, I missed a mask on sprite indexing when converting the nall integer template types to wider standard integer types, thanks. That would've been a big one for a release if not caught ^^;
