### ISSUE TITLE
Adventures of Dr. Franken, The (Europe) [bsnes v108.11][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#60]
Fast PPU on (same with snes9x 1.60 btw):
![A1](https://user-images.githubusercontent.com/53529402/63505877-a1500e80-c4d4-11e9-9d13-3690c484cd25.png)

Fast PPU off and Mesen-S:
![A2](https://user-images.githubusercontent.com/53529402/63505897-aad97680-c4d4-11e9-8bd4-cafcd7cdc274.png)

No problems at all with USA version.

**Comment by Screwtapello** [comment]
Obviously there's that line of garbage pixels, which is probably just a natural consequence of a scanline PPU if Snes9x does the same thing, but what about those corner-pieces around the selected flag? Do they blink, or are they always white on the slow PPU, and always black on the fast PPU?

**Comment by Max833** [comment]
No, they blink with and without PPU fast.

**Comment by byuu** [comment]
A lot of SNES games write to display registers in the middle of the scanline. We used to carefully curate and select exactly when to latch registers to be as compatible as possible with games. But this is also why the accurate PPU core exists.

Fixing Dr. Franken causes scanline issues in other games, so there's not a lot I can do short of maintaining a per-game database of 'points to render scanlines at', which is a bit extreme.

**Comment by Max833** [comment]
I see. Than I won't report scanline issues anymore.

**Comment by byuu** [comment]
![Screenshot_2019-08-24_09-06-38](https://user-images.githubusercontent.com/2107894/63602728-14f03980-c603-11e9-9854-57a04c0f0ab9.png)

Tell you what, go ahead and report these at your leisure, friend. I'll add overrides for the render cycle positions to give good out-of-the-box experiences for everyone ^-^
