### ISSUE TITLE
Arcade's Greatest Hits - The Atari Collection 1 (USA) [bsnes v108.11][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#61]
Game: "Asteroids"

Fast PPU on: https://streamable.com/2qxns
Fast PPU off, snes9x and Mesen-S: https://streamable.com/0iki6

That's it for now. I tested ~150 Games. ^^; A few issues I noticed with fast ppu off, I posted over there: https://github.com/byuu/bsnes/issues/55 Maybe that's helpful when you have more information about the PPU.

**Comment by byuu** [comment]
Should be fixed now, I believe this was the same sprite masking error. Please reopen if not ^-^;
