### ISSUE TITLE
Battle Blaze (USA) (Beta) - black flickering [bsnes v108.12][Fast PPU on and off]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#63]
This just happens with "Battle Blaze (USA) (**Beta**)" (fast PPU on **and** off). You have to choose "The Battle" and right before the fight starts, at the top there is a black flickering (after "Battle Start!" disappears).

 Edit: Both, snes9x and Mesen-S, have the same issue.

https://streamable.com/s0e8y

![12](https://user-images.githubusercontent.com/53529402/63629890-bc766780-c615-11e9-9226-43d0f958157a.jpg)

**Comment by byuu** [comment]
Yeah Battle Blaze is another game that writes to display registers mid-scanline. I'll add another override render cycle for it then.

**Comment by byuu** [comment]
Doesn't happen here, try the latest nightly, it may have been in the last round of fixes.

**Comment by Max833** [comment]
I have the latest nightly, but I noticed this isn't always there. Probably 30% of the time and sometimes not that big. And a little correction: Both, snes9x and Mesen-S, have the same issue. ^^;

**Comment by byuu** [comment]
If every emulator has the issue periodically, then it's almost certainly an issue on the real system as well. Can't hurt to verify though.

**Comment by Max833** [comment]
Maybe it has something to do with this mosaic effect?

![1](https://user-images.githubusercontent.com/53529402/63634751-ffa6f980-c65a-11e9-9cf4-a0342113775c.jpg)

**Comment by byuu** [comment]
If memory serves, Battle Blaze is supposed to do that mosaic glitch at the top right. Mosaic counters are batshit insane on the SNES.

**Comment by Max833** [comment]
> This just happens with "Battle Blaze (USA) (Beta)" (fast PPU on and off). You have to choose "The Battle" and right before the fight starts, at the top there is a black flickering (after "Battle Start!" disappears).

Hardware: https://streamable.com/khem8 (01:19)

![image](https://user-images.githubusercontent.com/53529402/63976422-92a7bf80-cab1-11e9-8771-b9bd46200148.png)


Respect. bsnes is insanely accurate. =)
