### ISSUE TITLE
Bishoujo Senshi Sailor Moon S - Kondo wa Puzzle de Oshioki yo! (Japan)

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#65]
**PPU fast on, SNES9x and Mesen-S:**
![2](https://user-images.githubusercontent.com/53529402/63639026-5af2df00-c68f-11e9-90f5-b5ee57943f5c.png)

**PPU fast off:**
![1](https://user-images.githubusercontent.com/53529402/63639024-56c6c180-c68f-11e9-8f67-081f515a147a.png)

Higan v106:
![j](https://user-images.githubusercontent.com/53529402/63639042-a1483e00-c68f-11e9-990e-944c859d8a1f.png)

**Comment by Max833** [comment]
bsnes and Mesen-S:
![asdf](https://user-images.githubusercontent.com/53529402/63639177-b4a7d900-c690-11e9-8a46-bc8c2bb2a333.png)

SNES9x:
![fdsa](https://user-images.githubusercontent.com/53529402/63639185-cab59980-c690-11e9-90fc-a6c37f282830.png)

**Comment by byuu** [comment]
I really appreciate your help, but can you please slow down with these? I'm just one person ._.;

**Comment by byuu** [comment]
The second one needs Settings->Output->Blur Emulation checked. It's using pseudo-hires to blend two graphics layers together.

The reason you notice it is because LCDs are so much sharper than CRTs and don't bleed colors. As a fun example, step back about 2-3 feet from your monitor and it will look correct even without blur emulation.

**Comment by byuu** [comment]
The first one, the game's placing all its unwanted sprites there.

There's an issue in that the two PPU cores render effects differently there, of course. Probably worth looking into. I feel like that's likely to come up in other games.

**Comment by Max833** [comment]
Thanks byuu! 
> Probably worth looking into. I feel like that's likely to come up in other games.
We'll see about that. :) I'm not sure how long it takes, but I'll test them all. ^^;

**Comment by Max833** [comment]
The matter has resolved itself, @byuu. ^^

Hardware behaviour:
![4e9fb885-0851-4889-b93kaf](https://user-images.githubusercontent.com/53529402/63944888-b566b380-ca72-11e9-9415-6ead14f17d95.jpeg)
