### ISSUE TITLE
Super Mario RPG (USA) locks up during the introduction

### ISSUE THREAD

**Issue by brushtool** [byuu/bsnes#66]
Reproduce by playing to the battle with the four Terrapins in Bowser's Castle, and winning the battle. You should see the overworld lock up, and everything will be frozen, apart from the audio.
Tested on v108.13 Windows. Tried different drivers, to no avail. Happens with both fast and slow PPU, coprocessors, etc.

**Comment by Max833** [comment]
I can confirm that and this doesn't happen with Higan v106, byuu.

**Comment by byuu** [comment]
Can a save RAM be produced (not save state) that gets me closer to where this event triggers?

**Comment by Max833** [comment]
This event triggers right after the intro.

Freeze with fast PPU off: Right after the intro (first red door).
Freeze with fast PPU on: Right after the battle with the four Terrapins and before Bowser (second red door).

**Comment by byuu** [comment]
That's too far in. To track the regression means using previous versions of the emulator, where the save state format changes. I'd have to play the game to that point potentially 20+ times to find the exact commit that caused the issue.

**Comment by brushtool** [comment]
> 
> 
> That's too far in. To track the regression means using previous versions of the emulator, where the save state format changes. I'd have to play the game to that point potentially 20+ times to find the exact commit that caused the issue.

There are no save points before the point where it crashes.

**Comment by byuu** [comment]
Oh okay, this isn't actually that far in. I thought I recalled there being a long intro sequence. I think I was thinking of the GBA version (Superstar Saga.) Okay, looking into it.

**Comment by byuu** [comment]
Fixed in the latest commit, thanks.
