### ISSUE TITLE
Bubsy II (Europe) - freeze [bsnes 108.13][DSP (audio) fast mode]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#67]
- wait until the game starts (titlescreen)

- the second level ("bach in time") freezes with bsnes ~40% of the time at exactly 0:12. No problems with Snes9x, Mesen-S and bsnes (***edit***) without DSP (audio) fast mode.

![Bubsy II (Europe)-001](https://user-images.githubusercontent.com/53529402/63650852-6574ad80-c74f-11e9-8a6f-f33f125b7ec9.png)
![Bubsy II (Europe)-002](https://user-images.githubusercontent.com/53529402/63650853-673e7100-c74f-11e9-9c43-e07bb89c4430.png)

**Comment by Max833** [comment]
"Fast PPU on" doesn't seems to be the problem. Just when I enable "DSP (audio) fast mode", the game freezes.

**Comment by byuu** [comment]
Okay easy enough, I have an override setting to disable the fast DSP. Thanks!

**Comment by byuu** [comment]
I don't know *which* second level, there's like eight levels you can choose at the start. But I'll take your word for it being an issue. The latest commit forces fast DSP off for this title, thanks.

**Comment by Max833** [comment]
Thanks! You don't have to choose anything. I don't know how it calls, but when you just wait... after ~10 seconds the CPU plays ~4 levels and it's the second level ("bach in time").

**Comment by Screwtapello** [comment]
@Max833, [attract mode](https://en.wikipedia.org/wiki/Glossary_of_video_game_terms#attract_mode) might be the phrase you're looking for.

**Comment by Max833** [comment]
Ah, okay. That's how it calls. Thanks! ^^'
