### ISSUE TITLE
Captain Novolin (USA) (En,Fr,Es) - scanlines [bsnes 108.13]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#68]
I wasn't sure to post this at all, because it's **really** trivial, but because of that fact that every emulator (SNES9x, Mesen-S, higan) reacts a little bit different... well, maybe it's helpful. Please do not hesitate to let me know if this kind of report is unnecessary.

ppu fast **on**: https://streamable.com/zeu7a **0:08** and **0:15** (0:15: as soon as you finish a level, you are getting the same screen)

ppu fast **off**: https://streamable.com/vpza3 **0:08** and **0:23**

At the very start there is a red scanline on the upper left side too (Fast PPU on).

**Comment by byuu** [comment]
We definitely need to get you an SNES and a flash cart ^-^
If you're interested, let me know if I can help with that.
Full library testers are exceedingly rare. You're the third person to have ever done this for bsnes.
It's very useful work, but there's so many glitches in real games ...

**Comment by Max833** [comment]
Oh, thanks! I appreciate your help with this, byuu. I already bought a flash cart yesterday (sd2snes pro). Soon we know more about those games. =)

**Comment by byuu** [comment]
Oh wow, that's awesome!! :D

**Comment by Max833** [comment]
Hardware: https://streamable.com/a2fyv (0:40, 01:34, 03:27, 04:02)

So yeah, pretty much hardware behaviour. ^^
