### ISSUE TITLE
Circuit USA (Japan) (En) - menu bug [Fast PPU on and off]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#69]
This happens not always and it doesn't look as bad as https://github.com/snes9xgit/snes9x/issues/563#issue-486666833, but sometimes the game menu isn't quite correct:

![image](https://user-images.githubusercontent.com/53529402/63900945-d98aac00-ca02-11e9-9a49-264bb8f48226.png)

I could never reproduce this with "Reset System".When it doesn't look right (via load rom) and I reset the system, it works again.

**Comment by Max833** [comment]
Couldn't reproduce this issue with hardware either.

**Comment by Screwtapello** [comment]
Does bsnes still have the "randomise memory at bootup" behaviour from higan?

**Comment by Max833** [comment]
Probably totally different problems, but "Circuit USA", "Beavis and Butt-Head" and "Captain Tsubasa IV" work perfectly well with higan v106.

**Comment by byuu** [comment]
![Screenshot_2019-08-31_06-43-19](https://user-images.githubusercontent.com/2107894/64052746-a7bc4580-cbba-11e9-9294-81a485cc1262.png)

I can't reproduce this with either the fast PPU or accurate PPU. I suspect the recent HDMA alignment fix for Battle Grand Prix also fixed this game.

**Comment by Max833** [comment]
It's still there (Windows 10 Pro, Version 1903), but "Captain Tsubasa IV" and "Beavis and Butt-Head" are fixed. Thanks, byuu! =)

I'll test this game with a different pc in the coming days.
