### ISSUE TITLE
New Mac error

### ISSUE THREAD

**Issue by azoreseuropa** [byuu/bsnes#7]
Compiling ../hiro/hiro.cpp ...
Compiling ../ruby/ruby.cpp ...
In file included from ../ruby/ruby.cpp:23:
In file included from ../ruby/video/video.cpp:2:
../ruby/video/cgl.cpp:165:10: error: too few arguments to function call,
      expected 2, have 0; did you mean 'ruby::VideoDriver::output'?
  video->output();
         ^~~~~~
         ruby::VideoDriver::output
../ruby/video/video.hpp:31:16: note: 'ruby::VideoDriver::output' declared here
  virtual auto output(uint width = 0, uint height = 0) -> void {}
               ^
1 error generated.
make: *** [obj/ruby.o] Error 1

**Comment by byuu** [comment]
Thanks! Fixed, need to make the cgl:165 line say video->output(0, 0);
Will be in the next push. Fair warning though, LIJI built the macOS port and while it runs, it's not really polished ...
