### ISSUE TITLE
Captain Tsubasa IV - Pro no Rival-tachi (Japan) - flickering at start up/reset [Fast PPU off]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#72]
Fast PPU off: https://streamable.com/r3ihb

There are no problems with "Fast PPU on" and hardware.

**Comment by byuu** [comment]
These are getting a little too specific to keep up with on an issue tracker ... we may want to come up with a better way of organizing very minor edge cases like this. Would you be up for using a forum for grouping all of these together? Perhaps a thread on https://helmet.kafuka.org/bboard/forum.php?id=3 could work.

**Comment by byuu** [comment]
Actually I can just put it on my site. The main issue is getting the reports to me. I have all the various chat clients and social media accounts and such, so anything there'd be fine. Would this work for you? The work here is awesome and I do appreciate it of course ^-^

**Comment by Max833** [comment]
For me, the most comfortable method would be that I can create here new issues and you decide what to do with them. You know, I don't have the technical expertise. I have no idea what's a very minor edge case and what's not. ^^' Or... I can create a thread over there (helmet.kafuka.org) and just update my list from time to time? Is this better?

**Comment by byuu** [comment]
I mean the primary issue is that there's no real way to categorize issues here, they all just show up in a single list, so it obscures more serious concerns like the SGB audio issue. That's not to say it's not important or appreciated, it definitely is. But it feels like really minor glitches work better in a list form. Well, go ahead and keep submitting them however it's comfortable for you, I'll come up with something in the mean time. Thanks again, happy you received your sd2snes! :D

**Comment by Screwtapello** [comment]
I suspect there's going to be a bunch fewer of these issues now that @Max833 has an SD2SNES and can do hardware verification on his own.

I think keeping each problem as an individual issue is good (there's nothing worse than looking at a 10-page forum thread and trying to figure out which posts are reporting new issues, and which posts are reporting a previous issues as solved), but they're definitely a separate category.

How about we use GitHub's "issue labels" feature? Create a label named "compatibiity" or something, let @Max833 tag each of his issues with that label, and then in the issue search field you can put `label:compatibility` to only show those issues, or `-label:compatibility` (with an initial `-`) to hide them.

**Comment by byuu** [comment]
> I suspect there's going to be a bunch fewer of these issues now

Another thing to keep in mind was there were definitely serious regressions on account of chasing so many performance gains recently. Fixing those in the A-C games are going to have knock-on effects in the D-Z games.

I feel awful complaining here, but I don't think a straight list of issues is a productive strategy. This is GitHub's fault, and Max is doing exceptionally valuable work that few if any people ever do (he's the third person in 15 years to do this!) But yeah, what I imagine for a bug tracker is having severity rankings. Every single issue should ideally be fixed, but Super Mario RPG crashing was definitely 1000x more important than a blink once in the intro. However, the blink indicates an issue, and that issue may appear in other games, so it does need to be fixed too.

I guess what I'm saying is, I'll use GitHub like everyone wants me to, but I don't really like GitHub.

> How about we use GitHub's "issue labels" feature?

That would be a viable strategy if we could set the default filtering to show issues labeled bugs first, help wanted second, the rest third.

**Comment by byuu** [comment]
The game is turning on the screen without initializing the PPU registers. The accuracy PPU randomizes all of the registers at startup. It's possible I am randomizing some registers I should not, but I am erring on the side of caution. The goal is to prevent new SNES developers from producing software that doesn't run on the real thing.

In any case, I exposed a new entropy setting under settings->emulation. If you set it to "None", the flickering will go away in this title, movie recordings (eg RPM Racing) will be more consistent, and old copier-based homebrew (eg Goodbye, Anthrox) will work. If you set it to "High", you can stress-test your games before releasing them with way higher entropy (randomness) than a real SNES would have. The default right now is "Low", which means this flicker will be there in releases out of the box.

**Comment by Max833** [comment]
> If you set it to "None", the flickering will go away in this title [...]

Hmm... I can't even reproduce this issue with "high" now. It's completly gone. Thanks!
