### ISSUE TITLE
[SGB] Pokemon - Yellow Version - Special Pikachu Edition (USA, Europe) (CGB+SGB Enhanced) crash

### ISSUE THREAD

**Issue by benderscruffy** [byuu/bsnes#74]
using bsnes 108.14
doesnt detect the borders and the screen goes blank at the intro
![pokemon](https://user-images.githubusercontent.com/2696404/64074682-36c37d80-cce1-11e9-9cc9-5316d5ee0249.PNG)

**Comment by Max833** [comment]
That's the game boy core. It's probably a good idea to post this here: https://github.com/LIJI32/SameBoy/issues?q=is%3Aopen+is%3Aissue

**Comment by byuu** [comment]
Could be the Killer Instinct player-2 fix. If that's the case, then we need to do more reverse engineering work to figure out how player-select actually works.

**Comment by byuu** [comment]
Yeah, it's the Killer Instinct change. I've reverted it so Pokemon runs. Seems more important than defaulting to player-2 in Killer Instinct. But that means the KI bug is back. I'll open a new issue to track both of these.
