### ISSUE TITLE
Dino Dini's Soccer! (Europe) (En,Fr,De) freezes [Fast PPU on and off]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#75]
It's a little bit like this one: https://github.com/byuu/bsnes/issues/64

~20% of the time the game freezes here (you have to wait and don't press anything).

![image](https://user-images.githubusercontent.com/53529402/64081322-97fa4980-ccff-11e9-8272-7f4de3f4029d.png)

bsnes: https://streamable.com/xal5l (**Edit**: Couldn't reproduce this with SNES9x and Mesen-S.)

hardware: https://streamable.com/k6f93

**Comment by Max833** [comment]
I think I found the problem. "D-Force (USA)" with stock speed is terrible but with overclocking the slowdown is completly gone. And... yeah, I forgot to disable this feature. Seems to work now. I'm sorry. Enough for today. ^^'

![image](https://user-images.githubusercontent.com/53529402/64081825-7c467180-cd06-11e9-948b-94e586a96a56.png)

**Comment by byuu** [comment]
Ah no worries, glad you found the fix ^-^
