### ISSUE TITLE
Dirt Racer (Europe) (En,Fr,De) freezes

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#76]
This Super FX game freezes (no overclocking this time! ^^') right at the beginning (~30%). 

![image](https://user-images.githubusercontent.com/53529402/64083177-321bbb00-cd1b-11e9-884b-d7bedc1da040.png)

**Comment by byuu** [comment]
This is a bug in the original game that could happen on real SNES consoles.
It's reading uninitialized memory, and crashing if it's the wrong value.
Set entropy to none and it hangs every time.
I will just flat out state that this game is defective and shouldn't have shipped.
Nonetheless, I added a workaround. This would have *never* happened in higan :/

**Comment by Screwtapello** [comment]
Even if this wasn't an actual emulation bug, I'd like to thank @Max833 for filing it. I've always been annoyed that buggy games were "known", but there's no single public list of known game bugs. Even if Max doesn't find all of them, just the fact that he's writing things down in a public place, in a standard format, and taking screenshots and movies, is amazing.

If we just tag these game bugs so they're easy to find later, that'll be a great step forward.
