### ISSUE TITLE
Alt+F4 does not close bsnes + weird behavior after pressing in full-screen mode

### ISSUE THREAD

**Issue by Marat-Tanalin** [byuu/bsnes#80]
Looks like the only working ways to close bsnes are the standard Windows “Close” button and the “System” → “Quit” menu item. Tested with bsnes v108, v108.15 and the latest v108.17.

Also, in v108.15 and v108.17, `Alt+F4` in full-screen mode switches bsnes to windowed mode AND makes bsnes show black screen until a keyboard shortcut for toggling full-screen mode is pressed. That said, the music continues to play while bsnes shows black screen. Once the keyboard shortcut for toggling full-screen mode is pressed, the window resumes showing the game. In the stable v108, `Alt+F4` in full-screen mode does nothing.

**Comment by byuu** [comment]
I might be able to suppress Alt+F4 in fullscreen mode, but I have no easy way to make it close the base emulator since the video driver is an abstraction layer above the GUI. Good enhancement idea, thanks.

**Comment by Marat-Tanalin** [comment]
> I might be able to suppress Alt+F4 in fullscreen mode

It should _not_ be suppressed unless it’s a temporary workaround for the “black screen while still playing music” bug, which is obviously a bug and fixing it is not just an enhancement.

Note that `Alt+F4` is a _generic_ keyboard shortcut that works in any Windows application by default. Suppressing it means breaking basic Windows UI conventions.

Also note that switching to full-screen mode usually does not involve creating an extra window (see full-screen mode in any of native PC games), and pressing `Alt+F4` in full-screen mode means the user intends to close the application itself, not to close an unexpected extra full-screen window.

**Comment by byuu** [comment]
I understand that it should close the application, and I told you why it doesn't.

**Comment by Screwtapello** [comment]
Is there some way to make the full-screen window tell the regular window "hey, we should quit" when it gets a WM_CLOSE, instead of just closing? Or even just pretending that it got the "toggle fullscreen" hotkey?

**Comment by byuu** [comment]
It may be possible to send a synthetic WM_CLOSE at the ruby::Video::context() HWND handle. I don't like the tail wagging the dog with requests like this, though.

**Comment by Marat-Tanalin** [comment]
Doesn’t `PostQuitMessage(0);` work?

**Comment by kev4cards** [comment]
The Alt key does not select the menu anymore, either. It works on v107r1 but not v108 or later. I'm not sure if this is related in any way to the aforementioned situation. It would be nice to have back, but if you have intentions to keep it from selecting the menu (so it doesn't conflict with user wanting to use it as an input button, etc.), that's totally understandable.

**Comment by byuu** [comment]
If alt doesn't work, that's a separate bug and you can submit that. I have absolutely no idea why alt would stop working though.

As for the original bug, PostQuitMessage didn't work. Direct3D exclusive mode also hard-suppresses Alt+F4 completely, so I am choosing to do the same for non-exclusive mode.

The latest commit disables Alt+F4 in fullscreen mode. This is a good enough workaround for me. It also matches how things work on Linux/BSD/Xorg for me.

**Comment by Marat-Tanalin** [comment]
> PostQuitMessage didn't work.

Strange, [`PostQuitMessage()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postquitmessage) is the standard WinAPI way to close the entire app. Windows-specific issue, Windows-specific solution.

> The latest commit disables Alt+F4 in fullscreen mode. This is a good enough workaround for me. It also matches how things work on Linux/BSD/Xorg for me.

Fwiw, a good cross-platform UI is not a UI that looks and behaves the same way on all platforms. Intead, it’s a UI that carefully follows conventions specific for each single platform, so that it would look and perceive as native as possible and as user of the platform expects and used to.

**Comment by Marat-Tanalin** [comment]
> Good enhancement idea, thanks.

Did you consider suppressing Alt+F4 as that enhancement, or did you mean something else?
