### ISSUE TITLE
[PSA] Example of Overclocking Rendering Screen Incorrectly

### ISSUE THREAD

**Issue by kev4cards** [byuu/bsnes#87]
This really is not an issue, just an FYI/PSA. Setting the CPU overclock to anything at or above 125% will break the Super Mario Bros. 2 title and player select screens in Super Mario All-Stars. This equates to 236 additional scanlines after NMI in Mesen-S (with 0 additional scanlines before NMI). The game can max out on "scanlines before" without issue. Feel to free close whenever you like.

![image](https://user-images.githubusercontent.com/21962903/64392671-d0f62f00-d01b-11e9-90d9-6b4917f9985e.png)

**Comment by byuu** [comment]
Thanks for letting me know. Eventually I'd like a games database that includes things like "max safe overclock" for games, but we're a ways off from that still. Good to have this on file somewhere though.
