### ISSUE TITLE
[Super Game Boy] From TV Animation One Piece - Maboroshi no Grand Line Boukenki! (Japan) (SGB Enhanced) (GB Compatible) glitches

### ISSUE THREAD

**Issue by benderscruffy** [byuu/bsnes#89]
using bsnes v109
during conversions the dialogue box is on the top of the screen it shakes and has a glitchy line down the bottom of the dialogue box
![from](https://user-images.githubusercontent.com/2696404/64408282-ea00ed80-d0b8-11e9-929f-c695cb19e5d7.PNG)
 but when the dialogue box is down the bottom there is no problems at all
![from1](https://user-images.githubusercontent.com/2696404/64408290-eec5a180-d0b8-11e9-8f97-9cfa79c39694.PNG)

**Comment by byuu** [comment]
Issue with SameBoy, not bsnes.
