### ISSUE TITLE
[Super Game Boy] Zen - Intergalactic Ninja (USA) graphic glitch

### ISSUE THREAD

**Issue by benderscruffy** [byuu/bsnes#91]
using v 109
going through the super gameboy
during the intro the head is too far down
you are supposed to see his mouth and neck
![zen](https://user-images.githubusercontent.com/2696404/64414874-bfb62c80-d0c6-11e9-8ca5-3252686a0cdd.PNG)
this from the gameboy
![zen1](https://user-images.githubusercontent.com/2696404/64414897-c9d82b00-d0c6-11e9-9c0a-427633f325ea.PNG)

**Comment by endrift** [comment]
Isn't this a dupe of https://github.com/LIJI32/SameBoy/issues/90 ?

**Comment by byuu** [comment]
Issue with SameBoy, not bsnes.
