### ISSUE TITLE
Alt Key Does Not Activate Menu bar

### ISSUE THREAD

**Issue by kev4cards** [byuu/bsnes#92]
Both alt keys will not activate the menu bar in v108 onward. They will activate the menu bar in v107r1. I tried searching online about menu bar activation and the alt key to give better detail to the problem, but I could only come up with suppression techniques using AutoHotKey. The only thing to come out of that was virtual-key codes. Alt uses the constant name VK_MENU and a hexadecimal value of 0x12 when used by the system. Is it possible that another code got used where the system code should have been utilized, or something got lost in the higan-bsnes transfer/transition to GitHub? I think Windows cannot use ASCII (?) (as a scancode?) to perform a system command (see Key Codes section of https://docs.microsoft.com/en-us/windows/win32/learnwin32/keyboard-input for reference). The alt keys work fine as normal assigned inputs.

**Comment by byuu** [comment]
I have no *possible* idea what would have changed here, and I'm also not personally interested in trying to debug this. If someone else wants to take a look, please feel free, but I probably won't fix this myself.

**Comment by kev4cards** [comment]
I'm glad you were able to figure it out. Thanks for taking a looking into it. Sorry for the useless red herring stuff.

**Comment by byuu** [comment]
This is fixed, thanks. And no worries.
