### ISSUE TITLE
[Super Game Boy] Chiki Chiki Machine Mou Race (Japan) bottom part of screen missing

### ISSUE THREAD

**Issue by benderscruffy** [byuu/bsnes#94]
using v109
when run throgh super gameboy
missing bottom part of screen and hud
![chikki](https://user-images.githubusercontent.com/2696404/64468716-7d3e2f80-d15a-11e9-8379-9aba8e47b7e8.PNG)

**Comment by rtretiakov** [comment]
https://github.com/LIJI32/SameBoy/issues/185
This is an issue in SameBoy.

**Comment by byuu** [comment]
Pretty much all of these are. I don't feel bsnes is the right repository to be reporting SGB bugs to, as I am not in any way maintaining SameBoy personally, and won't be fixing them. But again, it's good to somehow track that these issues exist.

I'll set up a page on my site for these I think.

**Comment by jjfmz42015** [comment]
Asking respectfully. If somebody has so many issues is it worth using? I mean the core you replaced was it not less buggy? I don't know. I'm truly just asking. A big fan of bsnes just curious.

**Comment by Max833** [comment]
> But again, it's good to somehow track that these issues exist.

Suggestion: We track them over there: https://github.com/LIJI32/SameBoy/issues/199

**Comment by benderscruffy** [comment]
but then bug #95 works in the stand alone sameboy but not in Bsnes v109 so tracking them over there is still not the answer

**Comment by Max833** [comment]
That's why it's called "[Super Game Boy] issues".

**Comment by benderscruffy** [comment]
@byuu 
as I am not in any way maintaining SameBoy personally, and won't be fixing them
why add it in the first place why not just keep your own work as what happens if Lior Halphon stops working on it

**Comment by jjfmz42015** [comment]
@benderscruffy in all fairness you asking byuu that makes me think if you feel this way why not just use bsnes for snes and GB emulator for GB?

**Comment by benderscruffy** [comment]
im not being negative just wondering as isnt higan the differant emulators all his own work so why change

**Comment by Screwtapello** [comment]
SameBoy is a more accurate Game Boy emulator than higan's Game Boy emulator. Most importantly, SameBoy will improve over time without byuu having to fix it himself.

**Comment by byuu** [comment]
SameBoy isn't perfect, but no Game Boy emulator is.

higan's Game Boy core has more issues (look at the higan bug tracker), and since higan and bsnes are now forked, I don't want the added burden of maintaining two Game Boy cores.

If the higan Game Boy core ever hits 100% compatibility, then I'll do a one-time port of that into bsnes.

**Comment by byuu** [comment]
Issue with SameBoy, not bsnes.
