### ISSUE TITLE
[Super Game Boy] Lawnmower Man, The (Europe) cannot start a new game

### ISSUE THREAD

**Issue by benderscruffy** [byuu/bsnes#95]
using v109
when run through the super gameboy
doesnt detect the start button

**Comment by endrift** [comment]
This one may well be a bsnes-side issue since this game uses keypad IRQs instead of the normal polling. I'm not sure how those are hooked up to the SGB.

**Comment by byuu** [comment]
Issue with SameBoy, not bsnes.
